### ISSUE TITLE
Unable to load dynamic library Php::Extension::~Extension()

### ISSUE THREAD

**Issue by sdasun** [CopernicaMarketingSoftware/PHP-CPP#146]
I'm getting following error when I run php cli.
PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/libMyExtention.so' - /usr/lib/php5/20121212/libMyExtention.so: undefined symbol: _ZN3Php9ExtensionD1Ev in Unknown on line 0

c++filt of _ZN3Php9ExtensionD1Ev  is Php::Extension::~Extension()

**Comment by ashishpatel0720** [comment]
@sdasun , i am facing the same problem, can you tell me exactly how you fixed it.
thanks.
