### ISSUE TITLE
A different Write First Extension

### ISSUE THREAD

**Issue by davekimble2** [CopernicaMarketingSoftware/PHP-CPP#155]
Lubuntu 14.04 (amd64)
My PHP code for this 4 million loop takes over 5 seconds!
So I compiled and installed php-cpp OK.
Wrote my very first .cpp following functionwithparameters.cpp

```
#include <string>
#include <iostream>
#include <phpcpp.h>

void adjust_brightness(unsigned char*& pixel_values, int brightness)
{   int n = sizeof(pixel_values);
    for(int i=0; i<n; i++)
    {   int v = pixel_values[i] + brightness;
        if(v > 255) { v = 255; }
        if(v < 0) { v = 0; }
        pixel_values[i] = v;
    }
}

extern "C" 
{   PHPCPP_EXPORT void *get_module() 
    {   static Php::Extension extension("adjust_brightness", "1.0");
        extension.add("adjust_brightness", adjust_brightness);
        return extension;
    }
}
```

g++ says:
adjust_brightness.cpp:18:61: error: call of overloaded ‘add(const char [18], void (&)(unsigned char*&, int))’ is ambiguous
         extension.add("adjust_brightness", adjust_brightness);

It then produces a list of errors longer than the source itself.

I've tried all sorts of variations, but they all fail the same way - I thought this way avoided doing checks on the parameters, so why is it confused?

Files at http://www.davekimble.org.au/adjust_brightness/

**Comment by IntegralGit** [comment]
Happy new year may it bring happiness and infinite money!
