### ISSUE TITLE
how to get all $_POST, $_GET, $_FILES variables

### ISSUE THREAD

**Issue by hugdx** [CopernicaMarketingSoftware/PHP-CPP#156]
Hi,
When i want to get all variables from ``$_POST``, ``$_GET``, ``$_FILES`` or get a constant: ``__DIR__``,``__LINE__``.
i tried:
````
Php::Value post_data = Php::POST
````
i reviced a message: can't convert ``Php::Super`` to ``Php::Value``
``Php::POST``, ``Php::GET``,  ``Php::FILES`` is only supported to get a variable with specific key name

Thanks

**Comment by schoentoon** [comment]
That is because you are not supposed to retrieve the values from it like that, you're supposed to do something like ```Php::Value time = Php::POST["time"]```.

Regarding the constant, C++ has __LINE__ and __FILE__ which are rather similar to the __DIR__ and __LINE__ in php.

**Comment by hugdx** [comment]
in php, ``$_POST`` will hold all post data as array. i want to get all post data as array. how i can do it?

**Comment by schoentoon** [comment]
I'm afraid that currently indeed isn't possible, I will look into the options on adding this feature.

**Comment by hugdx** [comment]
@schoentoon Thanks.
I hope in next version we can used it. I am realy need it.

**Comment by EmielBruijntjes** [comment]
This works for me when using the master branch of PHP-CPP:

````c++
        for (auto &iter : Php::SERVER)
        {
            Php::out << iter.first << ": " << iter.second << std::endl;
        }
````

**Comment by hugdx** [comment]
@EmielBruijntjes It is not worked with me.
when i test your code, it is still return same error:
````
required from here
/opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/bits/range_access.h:48:5: error: "class Php::Super" has no member named "begin"
````
````
 error: no matching function for call to "begin(Php::Super&)"
````
Please fix it
