### ISSUE TITLE
Resolving INSTALL_LIB issue for lib64

### ISSUE THREAD

**Issue by jto888** [CopernicaMarketingSoftware/PHP-CPP#157]
With some searching I found the following Makefile code to recommend resolving an often encountered problem. Replacing the current INSTALL_LIB line with these 4 lines seems to work on my sampling of systems.

libdir.x86_64			=  ${INSTALL_PREFIX}/lib64
libdir.i686			=  ${INSTALL_PREFIX}/lib
MACHINE := $(shell uname -m)
INSTALL_LIB     		=   $(libdir.$(MACHINE))

Found this solution at:
http://stackoverflow.com/questions/9214056/how-can-i-make-a-makefile-determine-the-systems-lib-directory

I am not sure there is really variability allowed on the INSTALL_PREFIX, but I kept this consistent with existing Makefile.

**Comment by EmielBruijntjes** [comment]
It is not that simple. On my computer the output of `uname -m` is x86_64. However, the libraries on my system are still installed in /usr/lib (there is no /usr/lib64 directory).
