### ISSUE TITLE
Allocated objects don't get garbagecollected

### ISSUE THREAD

**Issue by svmaris** [CopernicaMarketingSoftware/PHP-CPP#158]
I'm using PHP-CPP to provide a simple wrapper for std::set to PHP. It seems that objects aren't garbage collected when the PHP var is going out of scope (even after manually running `gc_collect_cycles()`), which causes long running cli scripts to occupy a lot of memory and eventually be killed by the OOM killer.

One of the recent commits (a couple of days ago) seemed to have fixed the problem, but it only caused the allocated memory to be invisible to PHP (`memory_get_usage()` and `memory_get_peak_usage()` don't report it). The PHP-process itself still takes a lot of memory, which does not get freed.

Additionally, commit fb80367d418f9a9fb059c98d5aec80febeb3bd23 seem to have broken my extension, because I'm not getting any return values.

**Comment by EmielBruijntjes** [comment]
Thanks for your feedback. Can you send a simple example that triggers your problem?

**Comment by svmaris** [comment]
Thanks for your quick reply.

I can't seem to reproduce the garbagecollection-issue I mentioned above, but I do still have the other two issues.

Regarding fb80367d418f9a9fb059c98d5aec80febeb3bd23:

This is what my `std::set::union()`-wrapper looks like:

```cpp
    Php::Value idset_or(Php::Parameters &params)
    {
        Php::Value arg = params[0];
        IdSet *set2 = (IdSet *)arg.implementation();
        std::set<int64_t> dest;
        std::set_union(_set.begin(), _set.end(), set2->_set.begin(), set2->_set.end(), std::insert_iterator< std::set<int64_t> >(dest, dest.begin()));
        IdSet *s = new IdSet();
        s->_set = dest;
        Php::Value self(this);
        Php::Value class_name = Php::call("get_class", self);
        return Php::Object(class_name, s);
    }
```

Without fb80367d418f9a9fb059c98d5aec80febeb3bd23 it works fine, but after this patch the following code:

```php
<?php
$set1 = new IdSet();
$set1->add(1);
$set2 = newIdSet();
$set2->add(2);
$set3 = $set1->or($set2);
```

FATAL's with the following error:

`Assigning an unassigned object to a variable`

Regarding the invisible memory: `memory_get_usage(true/false)` and `memory_get_peak_usage(true/false)` don't seem to report any of the memory occupied by the `IdSet`, even after adding a couple of million elements:

```php
<?php
$start = memory_get_usage(true);
$idSet = new IdSet();
for($i=0; $i < 5000000; $i++) {
    $idSet->add($i);
}
echo number_format(memory_get_usage(true)-$start)).PHP_EOL;
```

... shows about 32kb of memory consumed, which would be awesome if it were true :)

This was not the case before upgrading PHP-CPP (about 2 months ago).

**Comment by EmielBruijntjes** [comment]
Your code same was not complete. I wrote the following simple extension that basically does the same:

````c++
/**
 *  IdSet.cpp
 *
 *  PHP extension that works with a set of ids
 *
 *  @author Emiel Bruijntjes <emiel.bruijntjes@copernica.com>
 *  @copyright 2014 Copernica BV
 */
#include <phpcpp.h>
#include <set>
#include <iostream>

/**
 *  Class definition
 */
class IdSet : public Php::Base
{
private:
    /**
     *  Implemented as a real set
     *  @var std::set
     */
    std::set<int> _ids;
    
public:
    /**
     *  Constructor
     */
    IdSet() {}
    
    /**
     *  Destructor
     */
    virtual ~IdSet() {}
    
    /**
     *  Add an id to the set
     * 
     *  This method accepts a variable number of arguments
     * 
     *  @param  params      All parameters passed to the method
     *  @return Value       Same object for chaining
     */
    Php::Value add(Php::Parameters &params)
    {
        // loop over the params
        for (int i=0; i<params.size(); i++)
        {
            // convert param to an int
            int param = params[i];
            
            // add to the set
            _ids.insert(param);
        }
        
        // return 'this' to allow chaining
        return this;
    }
    
    /**
     *  Create a new set that holds all the ids in the current object and the 
     *  passed in sets.
     * 
     *  This method accepts a variable number of arguments
     * 
     *  @param  params      All parameters passed to the method
     *  @return Value       A new IdSet object holding all the ids
     */
    Php::Value merge(Php::Parameters &params)
    {
        // create a new set holding a copy of the current object
        auto *result = new IdSet(*this);
        
        // loop through the parameters
        for (int i=0; i<params.size(); i++)
        {
            // get the set
            auto otherset = params[i];
            
            // it must be an id-set
            if (!otherset.instanceOf("IdSet")) continue;
            
            // get the base implementation
            IdSet *other = (IdSet*)otherset.implementation();
            
            // loop through the ids in the other set
            for (auto &iter : other->_ids) result->_ids.insert(iter);
        }
        
        // use the Php::Object to wrap the new set in a valid PHP userspace object
        return Php::Object("IdSet", result);
    }
    
    /**
     *  Print the object
     */
    void print()
    {
        // loop through the ids
        for (auto &iter : _ids) Php::out << "member: " << iter << std::endl;
    }
};


/**
 *  Switch to C context
 */
extern "C" {

    /**
     *  The get_module() function that returns all extension properties
     *  @return void*
     */
    PHPCPP_EXPORT void *get_module() 
    {
        // the actual extension object
        static Php::Extension extension("IdSet", "1.0");

        // we are going to define a class
        Php::Class<IdSet> idset("IdSet");

        // the class methods that should be available
        idset.method("add", &IdSet::add);
        idset.method("merge", &IdSet::merge);
        idset.method("print", &IdSet::print);

        // add the class to the extension object
        extension.add(idset);
        
        // done
        return extension;
    }
}
````

It does seem to work now. I used the following simple PHP script to test it:

````php
<?php

$set1 = new IdSet();
$set2 = new IdSet();
$set1->add(1,2,3);
$set2->add(3,4,5);
$set3 = $set2->merge($set1);


$set1->print();
$set2->print();
$set3->print();
````

Does the recent changed solve your problem too?

About the memory thing: I've not looked into it, but PHP has its own memory management functions (emalloc, efree, et cetera). Maybe the memory_get_usage() function only reports the allocated memory that used those special functions. Your extensions uses a normal `new` and that memory allocation is therefore not managed by the Zend engine.

**Comment by svmaris** [comment]
Thanks Emiel, the missing `executestate.h` seemed to have caused the problem. The extension is working again.

You're probably right about `memory_get_usage()` only reporting memory from the Zend engine, but I'm pretty sure I've seen it working in the past, because I've compared the memory usage of different implementations (`Array` vs `SplFixedArray` vs. `std::set`). Not a real issue, but it makes debugging a bit difficult, because I'm not quite sure if/when the underlying `std::set` is destroyed when I `unset()` the PHP-variable. My code allocates multiple large sets and I need to make sure memory is returned to the OS *during* execution.

I should probably add some cleanup-code to `~IdSet()`, like `_ids.clear()`.

Thanks again for your elaborate response :)
