### ISSUE TITLE
Php::eval() is not worked

### ISSUE THREAD

**Issue by hugdx** [CopernicaMarketingSoftware/PHP-CPP#159]
````
void helloWorld ()
{
    Php::eval("echo 'called';");	
}
````
when i try with this function, i get an error:
````
Parse error: syntax error, unexpected 'echo' (T_ECHO) in  on line 1
````
with version for fix #149 , it was worked well.

**Comment by EmielBruijntjes** [comment]
Difficult problem. The fix that you mentioned was necessary to solve that eval() crashed when a value was returned from it. However, by fixing it, we now have this different problem which comes from the fact that the Zend engine modifies the code if you're interested in the return value of an eval() call (and the Php::eval() function does want to know the return value). In that case the Zend engine puts a "return" statement in front of the to-be-evaluated code. Your code is thus turned into `"return echo 'called';"`, which is indeed invalid.

However, I've decided to fix it. This may break programs that use programs like `auto result = Php::eval("3 + 5");`, but it now is more compatible with the builtin `eval()` function of PHP.

**Comment by hugdx** [comment]
@EmielBruijntjes  Thanks

**Comment by hugdx** [comment]
Hi @EmielBruijntjes 
i tried with 
````
Php::eval("echo 'called';"); 
```` 
i got error:
````500 Internal Server Error````

This is log on server:
```
[Fri Mar 20 16:03:39 2015] [error] [client 192.168.1.103] Premature end of script headers: test.php
````

I am using ``PHP-CPP`` version ``1.3.1``, ``g++ 4.8.2``. Please check and fix it. Thanks!
