### ISSUE TITLE
[NFR] Runtime Constants

### ISSUE THREAD

**Issue by tugrul** [CopernicaMarketingSoftware/PHP-CPP#160]
PHP's `define` and `defined` functions could be implemented. 

```cpp
namespace Php {

class Constant {
public:

// to check constant is defined before
static bool defined(std::string); 

// try to define a constant. return false if constant defined before. return true if a defined a constant as a new
static bool define(std::string); // to define a null valued constant
static bool define(std::string, Php::Value); 

static Php::Value get(std::string); // return value of the constant if defined. return null in other case

}
}
```

Implementations:
https://github.com/php/php-src/blob/master/Zend/zend_builtin_functions.c#L882
https://github.com/php/php-src/blob/master/Zend/zend_builtin_functions.c#L791

APIs:
https://github.com/php/php-src/blob/master/Zend/zend_constants.h

**Comment by hugdx** [comment]
it will be amazing if we can add it to php-cpp

**Comment by andot** [comment]
I already push this patch in https://github.com/CopernicaMarketingSoftware/PHP-CPP/pull/130

**Comment by tugrul** [comment]
Thank you @andot. Is could be better to group into `class Constant`? So there is `goto label` and we can need to `private static` overloaded method for Value and HashIterator to resolve `goto label` statement with recursive call.

Use case of the methods:
```cpp
// check constant is defined?
if (Php::Constant::defined("APP_ENV")) {
    // do something
}

// define a null valued constant to flagging statement of an app
Php::Constant::define("APP_STARTED");

// define a valued constant to changing runtime behavior
Php::Constant::define("APP_BASE_PATH", "/srv/www/myapp");

// get a value of the constant
Php::Value basePath = Php::Constant::get("APP_BASE_PATH");
```

**Comment by EmielBruijntjes** [comment]
We will soon come with an implementation and/or merge of the pull request

**Comment by EmielBruijntjes** [comment]
Based on code from the pull request, I just added some ways to work with constants from PHP-CPP scripts. The documentation for it can be found here: http://www.php-cpp.com/documentation/constants.

On a side note I'd like to give a warning: when you use PHP-CPP, it is in general for the performance best that your C++ code does not call other PHP-CPP functions. When an algorithm has finally left PHP user space and the Zend code, and runs in pure C++ code, the last thing you want to do is hand control back to slower Zend/PHP-CPP code.

````c++
/**
 *  Example of a smart C++ function, that only uses PHP-CPP to get away from PHP
 *  and from that moment on only calls fast C++ functions.
 */
void smart_function(Php::Parameters &params)
{
    // turn the slow PHP variables into fast C++ variables
    int param0 = params[0];
    std::string param1 = params[1];

    // @todo add your own fast implementation, using just native C++ code
}

/**
 *  Example of a stupid C++ function, that is written in C++, but that still calls back
 *  into slow PHP-CPP and Zend engine functions and variables.
 */
void stupid_function(Php::Parameters &params)
{
    // turn the slow PHP variables into other slow PHP variables
    Php::Value param0 = params[0];
    Php::Value param1 = params[1];

    // do slow PHP arithmetric
    Php::Value total = param0 * param1;

    // call a slow PHP function
    if (Php::array_key_exists(param0, param1)) { .... }

    // check for slow PHP constants
    if (Php::defined("SOME_CONSTANT")) { .... }

    // @todo add more slow calls to Php::whatever() and create more Php::Value instances
}
````
