### ISSUE TITLE
Install the PHP-CPP had some errors

### ISSUE THREAD

**Issue by han130634** [CopernicaMarketingSoftware/PHP-CPP#163]
hello,
I am a chinese ,i am a new php-cpp user.
I had execute the 'sudo make' command , and it success,But,when i compile the php-cpp,I found one error like the down code.
g++ -Wall -c -O2 -std=c++11 -fpic -I"/usr/local/PHP-CPP/tests/include/lib" -I"/usr/local/PHP-CPP/tests/include/zts" -o main.o main.cpp
In file included from h/variables.h:19:0,
from main.cpp:13:
h/../include/variables/011-012-value-casting-operators.h: In function ‘void TestVariables::value_casting(Php::Parameters&)’:
h/../include/variables/011-012-value-casting-operators.h:23:17: error: conversion from ‘Php::Value’ to ‘long int’ is ambiguous
long value1 = value;
.........
In file included from /usr/local/PHP-CPP/tests/include/lib/phpcpp.h:61:0,
from main.cpp:8:
/usr/local/PHP-CPP/tests/include/lib/phpcpp/class.h: In member function ‘Php::Value Php::Class::callToInteger(Php::Base) const [with T = TestVariables::Obj2Scalar]’:
/usr/local/PHP-CPP/tests/include/lib/phpcpp/class.h:451:5: warning: control reaches end of non-void function [-Wreturn-type]
}
^
make[1]: ** [main.o] Error 1
make[1]: Leaving directory `/usr/local/PHP-CPP/tests/cpp'
/usr/local/PHP-CPP:
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP/tests/ext_dir/extfortest.so: cannot open shared object file: No such file or directory in Unknown on line 0

PHP Warning: PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP/tests/ext_dir/extfortest.so: cannot open shared object file: No such file or directory in Unknown on line 0

PHP : /usr/local/php/bin/php 
Warning: PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP/tests/ext_dir/extfortest.so: cannot open shared object file: No such file or directory in Unknown on line 0

PHP_SAPI : cli
PHP_VERSION : 5.4.8
ZEND_VERSION: 2.4.0
PHP_OS : Linux - Linux hyqlinux 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:23:46 UTC 2014 i686
INI actual : /usr/local/php/lib/php.ini
More .INIs :

CWD : /usr/local/PHP-CPP/tests
Extra dirs :

VALGRIND : Not used

.........

Number of tests : 44 0
Tests skipped : 44 (100.0%) --------
Tests warned : 0 ( 0.0%) ( 0.0%)
Tests failed : 0 ( 0.0%) ( 0.0%)
Expected fail : 0 ( 0.0%) ( 0.0%)

Tests passed : 0 ( 0.0%) ( 0.0%)

Time taken : 1 seconds

I want to know the results of the above errors would affect?
Looking forward to your reply.
best wishes. 
thks.

**Comment by schoentoon** [comment]
First of all, you should execute ```sudo make```, you should run only run ```make install``` with sudo. Second of all, yes our tests don't exactly run.. And I'm not entirely what you are trying to compile and on what it errors. Could you provide some code which you are tying to compile?

**Comment by han130634** [comment]
ok,i got it.
The command sequence I executed . 
The first command is sudo make,then the message tips said I should 'make test',so I do it.And then the errors were occurred.As the above.I don't know why?I have try diffrent some version,but the errors always exist.In my way,I think it should be a variable type of problem.
Finally, I execute the 'sudo make install' command .
this is the result,I don't know the result is right or not:

mkdir -p /usr/include/phpcpp
cp -f phpcpp.h /usr/include
cp -f include/*.h /usr/include/phpcpp
if [ -e libphpcpp.so ]; then cp -f libphpcpp.so /usr/lib; fi
if [ -e libphpcpp.a ]; then cp -f libphpcpp.a /usr/lib; fi
if [ -e libhhvmcpp.so ]; then cp -f libhhvmcpp.so /usr/lib; fi
if [ -e libhhvmcpp.a ]; then cp -f libhhvmcpp.a /usr/lib; fi

please tell me the result.
thks

**Comment by hugdx** [comment]
````
from main.cpp:13:
`````
````
error: conversion from ‘Php::Value’ to ‘long int’ is ambiguous
long value1 = value;
````
change to 
````
long value1 = value.numericValue();
````

see more in ``include/value.h``
````
/**
     *  Retrieve the value as number
     *
     *  We force this to be a int64_t because we assume that most
     *  servers run 64 bits nowadays, and because we use int32_t, int64_t
     *  almost everywhere, instead of 'long' and on OSX neither of
     *  these intxx_t types is defined as 'long'...
     *
     *  @return int64_t
     */
    int64_t numericValue() const;
````

**Comment by han130634** [comment]
@hugdx thks.
I do the change for your way, but the new error were occurred.
I think the tarball I download was wrong. The errors info :

mkdir -p ./tests/include/zts/phpcpp
cd tests && ./test.sh -p "/usr/local/php/bin/php"
Compile the test extension
make[1]: Entering directory `/usr/local/PHP-CPP1/tests/cpp'
rm -f extfortest.so main.o
make[1]: Leaving directory `/usr/local/PHP-CPP1/tests/cpp'
make[1]: Entering directory `/usr/local/PHP-CPP1/tests/cpp'
g++ -Wall -c -O2 -std=c++11 -fpic -I"/usr/local/PHP-CPP1/tests/include/lib" -I"/usr/local/PHP-CPP1/tests/include/zts" -o main.o main.cpp
In file included from /usr/local/PHP-CPP1/tests/include/lib/phpcpp.h:61:0,
                 from main.cpp:8:
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/class.h: In instantiation of ‘Php::Value Php::Class<ANYTHING>::callToInteger(Php::Base*) const [with T = TestVariables::Obj2Scalar]’:
main.cpp:179:1:   required from here
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/class.h:450:63: error: call of overloaded ‘Value(long int)’ is ambiguous
         return Value(obj->__toInteger()).setType(Type::Numeric);
                                                               ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/class.h:450:63: note: candidates are:
In file included from /usr/local/PHP-CPP1/tests/include/lib/phpcpp.h:38:0,
                 from main.cpp:8:
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:132:5: note: Php::Value::Value(Php::Value&&)
     Value(Value &&that) noexcept;
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:126:5: note: Php::Value::Value(const Php::Value&)
     Value(const Value &that);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:120:5: note: Php::Value::Value(const Php::Base*) <near match>
     Value(const Base *base);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:120:5: note:   no known conversion for argument 1 from ‘long int’ to ‘const Php::Base*’
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:114:5: note: Php::Value::Value(_zval_struct*, bool) <near match>
     Value(struct _zval_struct *zval, bool ref=false);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:114:5: note:   no known conversion for argument 1 from ‘long int’ to ‘_zval_struct*’
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:61:5: note: Php::Value::Value(double)
     Value(double value);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:60:5: note: Php::Value::Value(const char*, int) <near match>
     Value(const char *value, int size = -1);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:60:5: note:   no known conversion for argument 1 from ‘long int’ to ‘const char*’
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:59:5: note: Php::Value::Value(const string&) <near match>
     Value(const std::string &value);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:59:5: note:   no known conversion for argument 1 from ‘long int’ to ‘const string& {aka const std::basic_string<char>&}’
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:58:5: note: Php::Value::Value(char)
     Value(char value);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:57:5: note: Php::Value::Value(bool)
     Value(bool value);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:56:5: note: Php::Value::Value(int64_t)
     Value(int64_t value);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:55:5: note: Php::Value::Value(int32_t)
     Value(int32_t value);
     ^
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/value.h:54:5: note: Php::Value::Value(int16_t)
     Value(int16_t value);
     ^
In file included from /usr/local/PHP-CPP1/tests/include/lib/phpcpp.h:61:0,
                 from main.cpp:8:
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/class.h: In member function ‘Php::Value Php::Class<ANYTHING>::callToInteger(Php::Base*) const [with T = TestVariables::Obj2Scalar]’:
/usr/local/PHP-CPP1/tests/include/lib/phpcpp/class.h:451:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/usr/local/PHP-CPP1/tests/cpp'
/usr/local/PHP-CPP1:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP1/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP1/tests/ext_dir/extfortest.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/PHP-CPP1/tests/ext_dir/extfortest.so' - /usr/local/PHP-CPP1/tests/ext_dir/extfortest.so: cannot open

My system is 32bit, my tarball is right or not .I Confused.
tks.

**Comment by EmielBruijntjes** [comment]
It are just the tests that are not working, is that right? My advise: do *not* run `make test`, just use PHP-CPP.
