### ISSUE TITLE
Magic methods not working in derived class

### ISSUE THREAD

**Issue by goddanao** [CopernicaMarketingSoftware/PHP-CPP#166]
I got this scenario:
 - a class (ZHandle) that extends Php::Base;
 - other classes (ZActor, ZSocket, ZProxy, etc) which extends ZHandle;

declaring __callStatic in ZHandle works as excepted, but declaring in ZActor not.
It's also impossible to make virtual a static in c++ (afik)

**Comment by EmielBruijntjes** [comment]
Can you send some example code that doesn't work like you expected?

**Comment by EmielBruijntjes** [comment]
I'm closing this issue until more information is received.
