### ISSUE TITLE
Compilation on raspberry b+

### ISSUE THREAD

**Issue by vdipietri** [CopernicaMarketingSoftware/PHP-CPP#168]
Hi
This is a first error

root@cirm ~/PHP-CPP # make
mkdir -p shared/common
mkdir -p shared/zend
mkdir -p shared/hhvm
g++ -Wall -c -g -std=c++11 -fpic -o shared/common/streambuf.o common/streambuf.cpp
cc1plus: error: unrecognized command line option ‘-std=c++11’
Makefile:205: set di istruzioni per l'obiettivo "shared/common/streambuf.o" non riuscito
make: *** [shared/common/streambuf.o] Errore 1
root@cirm ~/PHP-CPP # ls -la
totale 76
drwxr-xr-x 11 root root  4096 feb 10 17:31 .
drwxr-xr-x 20 1000 pi    4096 feb 10 17:30 ..
drwxr-xr-x  2 root root  4096 feb 10 17:30 common
drwxr-xr-x  2 root root  4096 feb 10 17:30 documentation
drwxr-xr-x 14 root root  4096 feb 10 17:30 Examples
drwxr-xr-x  8 root root  4096 feb 10 17:30 .git
-rw-r--r--  1 root root    19 feb 10 17:30 .gitignore
drwxr-xr-x  2 root root  4096 feb 10 17:30 hhvm
drwxr-xr-x  2 root root  4096 feb 10 17:30 include
-rw-r--r--  1 root root 10273 feb 10 17:30 LICENSE
-rw-r--r--  1 root root  7374 feb 10 17:30 Makefile
-rw-r--r--  1 root root  1909 feb 10 17:30 phpcpp.h
-rw-r--r--  1 root root  2544 feb 10 17:30 README.md
drwxr-xr-x  5 root root  4096 feb 10 17:31 shared
drwxr-xr-x  5 root root  4096 feb 10 17:30 tests
drwxr-xr-x  2 root root  4096 feb 10 17:30 zend

**Comment by EmielBruijntjes** [comment]
I think you're using a very old compiler that does not support C++11. C++11 support is essential for PHP-CPP, so best is to upgrade your compiler. What is the output of `g++ --version`?

**Comment by vdipietri** [comment]
c++ (Debian 4.6.3-14+rpi1) 4.6.3

2015-02-10 17:39 GMT+01:00 Emiel Bruijntjes <notifications@github.com>:

> I think you're using a very old compiler that does not support C++11.
> C++11 support is essential for PHP-CPP, so best is to upgrade your
> compiler. What is the output of g++ --version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/168#issuecomment-73733139>
> .
>



-- 


*Vincenzino Di Pietri*

*Consulente Informatico Progettista*


*System Integration,Telecomunicazioni,Reti*

00125 *Roma* (Italy)

Via dei Basaldella , 89

Tel. +39 06 5216317  Mobile: +39 348 3347371

**Comment by EmielBruijntjes** [comment]
You should upgrade to a newer version of the compiler, like g++ 4.9.*? PHP-CPP makes full use of new C++11 features, and your outdated compiler does not seem to support them.

**Comment by vdipietri** [comment]
Ok

Grazie from italy

regards
vincenzo

2015-02-10 17:45 GMT+01:00 Emiel Bruijntjes <notifications@github.com>:

> You should upgrade to a newer version of the compiler, like g++ 4.9.*?
> PHP-CPP makes full use of new C++11 features, and your outdated compiler
> does not seem to support them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/168#issuecomment-73734572>
> .
>



-- 


*Vincenzino Di Pietri*

*Consulente Informatico Progettista*


*System Integration,Telecomunicazioni,Reti*

00125 *Roma* (Italy)

Via dei Basaldella , 89

Tel. +39 06 5216317  Mobile: +39 348 3347371
