### ISSUE TITLE
Compilation failed for v1.3

### ISSUE THREAD

**Issue by mathieupotier** [CopernicaMarketingSoftware/PHP-CPP#170]
Hi all, seems that your 1.3 version is no more compiling due to ambiguous call for method.

Compiling using gcc 4.8.2 under raspbian (Raspberry Pi)

# Informations about GCC setup :
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.8.2-21~rpi3rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.8.2 (Raspbian 4.8.2-21~rpi3rpi1)

# Here is the error during make command :
mkdir -p shared/common
mkdir -p shared/zend
mkdir -p shared/hhvm
g++ -Wall -c -g -std=c++11 -fpic -o shared/common/streambuf.o common/streambuf.cpp
g++ -Wall -c -g -std=c++11 -fpic -o shared/common/modifiers.o common/modifiers.cpp
g++ -Wall -c -g -std=c++11 `php-config --includes` -fpic -o shared/zend/inivalue.o zend/inivalue.cpp
In file included from zend/includes.h:126:0,
                 from zend/inivalue.cpp:8:
zend/constantimpl.h: In member function ‘void Php::ConstantImpl::addTo(Php::ClassBase&) const’:
zend/constantimpl.h:131:69: error: call of overloaded ‘property(const char* const&, const long int&, const int&)’ is ambiguous
             clss.property(_name, Z_LVAL(_constant.value), Php::Const);
                                                                     ^
zend/constantimpl.h:131:69: note: candidates are:
In file included from zend/includes.h:79:0,
                 from zend/inivalue.cpp:8:
zend/../include/classbase.h:236:10: note: void Php::ClassBase::property(const char*, int16_t, int)
     void property(const char *name, int16_t value, int flags = Php::Public);
          ^
zend/../include/classbase.h:237:10: note: void Php::ClassBase::property(const char*, int32_t, int)
     void property(const char *name, int32_t value, int flags = Php::Public);
          ^
zend/../include/classbase.h:238:10: note: void Php::ClassBase::property(const char*, int64_t, int)
     void property(const char *name, int64_t value, int flags = Php::Public);
          ^
zend/../include/classbase.h:239:10: note: void Php::ClassBase::property(const char*, bool, int)
     void property(const char *name, bool value, int flags = Php::Public);
          ^
zend/../include/classbase.h:240:10: note: void Php::ClassBase::property(const char*, char, int)
     void property(const char *name, char value, int flags = Php::Public);
          ^
zend/../include/classbase.h:241:10: note: void Php::ClassBase::property(const char*, const string&, int) <near match>
     void property(const char *name, const std::string &value, int flags = Php::Public);
          ^
zend/../include/classbase.h:241:10: note:   no known conversion for argument 2 from ‘const long int’ to ‘const string& {aka const std::basic_string<char>&}’
zend/../include/classbase.h:242:10: note: void Php::ClassBase::property(const char*, const char*, int) <near match>
     void property(const char *name, const char *value, int flags = Php::Public);
          ^
zend/../include/classbase.h:242:10: note:   no known conversion for argument 2 from ‘const long int’ to ‘const char*’
zend/../include/classbase.h:243:10: note: void Php::ClassBase::property(const char*, double, int)
     void property(const char *name, double value, int flags = Php::Public);
          ^
Makefile:211: recipe for target 'shared/zend/inivalue.o' failed
make: *** [shared/zend/inivalue.o] Error 1

**Comment by EmielBruijntjes** [comment]
Does this also occur if you try to compile the master branche?

**Comment by mathieupotier** [comment]
No but using the master branch lead me to an execution error on loading the extension (The example empty extension) so I cannot use it either.

I'll retry this evening and provide you the exec error.
Do you want a separated ticket ?

Cordialement / Regards

Mathieu POTIER

**Comment by EmielBruijntjes** [comment]
The master branch is the best branch. You can report issues wherever you like. I suppose you're on a 32bit environment, aren't you?

**Comment by mathieupotier** [comment]
Yes, raspberry is 32bit.

Cordialement / Regards

Mathieu POTIER

**Comment by mathieupotier** [comment]
Up,

When compiling with dev-master 086cb94ad6aee856fd51ad8d7116f4a1c485a926
I got this error during PHP execution :

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525+lfs/phpeib.so' - /usr/lib/libphpcpp.so: undefined symbol: zend_next_free_module in Unknown on line 0

Is PHP-CPP still compatible with 32bit architecture ?

**Comment by EmielBruijntjes** [comment]
It should be compatible with 32bit, we ourselves only use it on 64bit platforms, but there is no code in it that would break it on 32bit platforms.

Phpeib.so is the extension that you're building? It's a weird error, the zend_next_free_module() function is simply available inside the Zend engine, so I see no reason why this is reported. Can you try to rebuild and re-install everything, PHP-CPP and your extension?

If you need a quick workaround, you can remove the call to zend_next_free_module() from the PHP-CPP code. This is not a problem as long as you don't use the Php::dl() function inside your extension.

**Comment by kamaroly** [comment]
@mathieupotier  how did you solve this issue? I am facing same thing

**Comment by kamaroly** [comment]
Hello Guys, I found the fix, download php source code at http://au1.php.net/distributions/php-5.6.6.tar.bz2 then extract it and find Zend (with Z capital) folder and rename it to zend and replace with the existing one in php-cpp (Not don't try to merge but replace the whole folder) this should fix the issue. I hope this is usefull

**Comment by EmielBruijntjes** [comment]
That is definitely _not_ a fix. The fix is to first install PHP on your system, and then compile PHP-CPP.

**Comment by schoentoon** [comment]
Installing just PHP might not be enough. You obviously will also need the headers and all, which are usually not included in just PHP installations.

**Comment by EmielBruijntjes** [comment]
On ubuntu, 'sudo apt-get install php5-dev' does the trick.
