### ISSUE TITLE
A C++ class implementing a Php interface ?

### ISSUE THREAD

**Issue by b-viguier** [CopernicaMarketingSoftware/PHP-CPP#179]
Hi,
I made some tests with PhpCpp, and I wonder if it is possible to use Php interfaces from popular libraries in order to create C++ native objects. I tried 2 things:

###### Define interface in C++ and Php ######
```c++
Php::Interface myPhpInterface("MyPhpInterface");
myPhpInterface.method("foo");
counter.implements(myPhpInterface);

extension.add(std::move(myPhpInterface));
extension.add(std::move(counter));
```

```php
interface MyPhpInterface
{
    public function foo();
}

function doSomething(MyPhpInterface $object)
{
    $object->foo();
}
```

But it produces a fatal: `Fatal error: Cannot redeclare class MyPhpInterface` ... seems normal!

###### Define interface in C++ but without adding it to extension  ######

Here the only difference with previous example
```c++
//extension.add(std::move(myPhpInterface));
extension.add(std::move(counter));
```

But here the result: `Catchable fatal error: Argument 1 passed to doSomething() must implement interface MyPhpInterface, instance of Counter given`. So I guess that the Php engine does not *see* that my C++ object implements `MyPhpInterface` since I didn't added it to the `extension`.

Maybe it is not possible for some legit technical reasons, so I just ask *people who know* :)

Thanks for your work!

**Comment by EmielBruijntjes** [comment]
The important thing to realize here, is that your extension is loaded _before_ the PHP user space code runs. Any interfaces and classes that are defined by PHP scripts, do not yet exist when your extension is initialized. It is therefore not possible to make a C++ class that implements a user space interface - the interface simply does not yes exist at that time.

**Comment by b-viguier** [comment]
Ok, it is clear for me now, I think I was expecting some *runtime magic* ;)
