### ISSUE TITLE
Failed to run example from documentation

### ISSUE THREAD

**Issue by spleshka** [CopernicaMarketingSoftware/PHP-CPP#181]
Hello,

I am trying to build the example from documentation here http://www.php-cpp.com/documentation/functions.

For phpcpp library "make" and "make install" worked without any problems. Also I was able to compile an example function from documentation into .so file. But when I tried to execute myFunction() from php it throws me error:

$php test.php

>PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/my_extension.so' - /usr/lib/libphpcpp.so: undefined symbol: zend_next_free_module in Unknown on line 0
>PHP Fatal error:  Call to undefined function myFunction() in /var/PHP-CPP/test.php on line 3

test.php file looks like this: <?php myFunction();

I would appreciate any help, because I really love the idea of php-cpp extension and want to contribute several performance improvements for php frameworks.

**Comment by spleshka** [comment]
When I was trying to run tests, all 44 tests were skipped. See header of test execution:

>mkdir -p ./tests/include/zts/phpcpp
>cd tests && ./test.sh -p "/usr/bin/php"
>Compile the test extension
>make[1]: Entering directory `/var/PHP-CPP/PHP-CPP-stable/tests/cpp'
>rm -f extfortest.so main.o
>make[1]: Leaving directory `/var/PHP-CPP/PHP-CPP-stable/tests/cpp'
>make[1]: Entering directory `/var/PHP-CPP/PHP-CPP-stable/tests/cpp'
>g++ -Wall -c -O2 -std=c++11 -fpic -I"/var/PHP-CPP/PHP-CPP-stable/tests/include/lib" -I"/var/PHP-CPP/PHP-CPP-stable/tests/include/zts" -o main.o main.cpp
>g++ -shared -L"/var/PHP-CPP/PHP-CPP-stable" -o extfortest.so main.o -lphpcpp
>make[1]: Leaving directory `/var/PHP-CPP/PHP-CPP-stable/tests/cpp'
>/var/PHP-CPP/PHP-CPP-stable:
>PHP Warning:  PHP Startup: Unable to load dynamic library '/var/PHP-CPP/PHP-CPP-stable/tests/ext_dir/extfortest.so' - /var/PHP-CPP/PHP-CPP-stable/libphpcpp.so: undefined symbol: zend_next_free_module in Unknown on line 0
>PHP Warning:  PHP Startup: Unable to load dynamic library '/var/PHP-CPP/PHP-CPP-stable/tests/ext_dir/extfortest.so' - /var/PHP-CPP/PHP-CPP-stable/libphpcpp.so: undefined symbol: zend_next_free_module in Unknown on line 0

So the same error happens in both cases:

>/var/PHP-CPP/PHP-CPP-stable/libphpcpp.so: undefined symbol: zend_next_free_module in Unknown on line 0

**Comment by valmat** [comment]
At first glance, you are using a different version of php to compile PHP-CPP and run your example. 
Could you tell which version of php do use.
Also, it may be your example was not installed correctly.
According to the data that you have provided, it is difficult to diagnose the cause.
Try uninstall your example extension and run tests after.
If some error occurs then, run following:
```
cd /path/to/PHP-CPP/tests
./test.sh -p /usr/bin/php -s /tmp/tests-out
```
and share file `/tmp/tests-out` for us, please.
It contains all debugging information about why tests were broken.
PS file `/tmp/tests-out` will be large. So don't put it here. You can use https://gist.github.com/, for example, or any other.

**Comment by spleshka** [comment]
> At first glance, you are using a different version of php to compile PHP-CPP and run your example
That is very unlikely, because I've installed php only once, and built extension and trying to execute it with the same php cli.

> Could you tell which version of php do you use?
PHP 5.4.36-0+deb7u3
Zend Engine v.2.4.0

> Also, it may be your example was not installed correctly.
Well, I just added my_extension.ini with extension=my_extension.so to conf folder. So even the error above confirms that php sees extension, but can't execute because some issue: It writes that unable to load extension, but not that the extension doesn't exist.

> and share file /tmp/tests-out for us, please
Here we go https://gist.github.com/spleshka/c803eefedd0189c5ae84

**Comment by EmielBruijntjes** [comment]
Your extension fails to load because it cannot find the symbol 'zend_next_free_module'. That's strange, because that symbol is defined in the Zend engine, so it must be there.

Are you sure that the PHP header files do match the PHP version that is installed on your system? Sometimes we see that someone uses the php installation that comes from the repository of the operating system, but download the headers directly from www.php.net. This causes a conflict.

Please check the output of `php-config --libs`, and try to add these flags to the linker when compiling PHP-CPP and your extension. It might work.

**Comment by spleshka** [comment]
Currently I have an idea that it can be the problem with line endings. Wait a bit, I'll recompile both extensions with correct line endings and let you know if it helps.

**Comment by spleshka** [comment]
Unfortunately it is not line endings issue. Trying to follow your suggestion with ```php-config --libs```.

**Comment by spleshka** [comment]
Well, you had a good idea - somehow not all libraries from ```php-config --libs``` can be found during compilation of extension, see https://gist.github.com/spleshka/04fb2be6e759ed7a22f1. Trying to understand how this issue can be solved.

**Comment by spleshka** [comment]
Btw, it might be a good idea to add a ```php-config --libs``` to ```LINKER_DEPENDENCIES``` variable from makefile.

**Comment by spleshka** [comment]
Okay, turns out that ```php-config``` tells me that I have ```php 5.4.4``` while ```php -v``` shows  me ````php 5.4.36```. You was absolutely right, somehow I have different php versions.

**Comment by EmielBruijntjes** [comment]
Yes, that was exactly the issue. There is a version difference between your PHP development environment, and the PHP runtime environment on your system. 

I don't think that the missing linker flags were the real problem, it was just an easy attempt to fix things.

**Comment by spleshka** [comment]
I agree, missing linker flags were not a problem. But I think it might be a good indicator that something goes wrong - it may save a lot of time for devs who will run into the same issue.

**Comment by EmielBruijntjes** [comment]
Most of the linker options are not at all necessary -- yes, i may help developers to set up their system, but in reality it does not make any sense to link either an extension or php-cpp with flags like -lbz2 or -lcrypto, because those libs are not used by PHP-CPP or your extension.

**Comment by spleshka** [comment]
Agree, it makes sense. 
Thanks indeed for your help with this issue.
