### ISSUE TITLE
Php::script does not resolve interfaces

### ISSUE THREAD

**Issue by mattriverm** [CopernicaMarketingSoftware/PHP-CPP#182]
Hello, any idea why this does not work:

    std::string phpscript = "interface face { public function nose(); } class myface implements face { public function nose() { return 'nose'; } }";
    Php::Script *s = new Php::Script(cls, phpscript.c_str(), phpscript.length());

while this does:

    std::string phpscript = "interface face { public function nose(); } class myface { public function nose() { return 'nose'; } }";
        
When I use the implementation of the interface php does not register the class myface. `script->valid()` says both are valid. Can I change some compiler flag or something?

Best regards // Matt

**Comment by valmat** [comment]
Hello.
`Php::Script` is a new feature of the PHP-CPP library, and i am not sure, but its [look](https://github.com/CopernicaMarketingSoftware/PHP-CPP/blob/master/zend/script.cpp) that you should to use `s->execute()`.
Let me ask. Why do you use so strange solution to declare an interface? PHP-CPP contains more natural way to declare interfaces: http://www.php-cpp.com/documentation/inheritance
In addition, the native way will be faster, looks better and easier to maintaining.

**Comment by EmielBruijntjes** [comment]
That is exactly the question that I wanted to ask. In general, it is a bad idea to use Php::Script, unless you have a very specific use case in which it is necessary. Defining an interface or class is in general not such a special use case.

And indeed, you need to call the execute() method.

**Comment by mattriverm** [comment]
I'm trying to write an extension that includes encrypted php files. So I have the decrypted php file as a string and I want to register the class "behind the scenes". It seemed like an easy way to use Php::script and I just wanted to try to understand what was going wrong. My apache segfaults when I use execute, and that is not necessary for the class to be registered. It's just that it does not work with php interfaces.
