### ISSUE TITLE
libphpcpp.so: undefined symbol: zend_next_free_module in Unknown on line 0

### ISSUE THREAD

**Issue by TigerZZ** [CopernicaMarketingSoftware/PHP-CPP#185]
php -v
PHP 5.5.23 (cli) (built: Mar 20 2015 07:50:26)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
php-config
 --version           [5.5.23]
 --vernum            [50523]

PHP-CPP v1.2.2 doesn't have any problem.
I try to mark out the "start()" from module.h with
//_entry->module_number = zend_next_free_module();

(PHP-CPP v1.3.2) The problem is sovled and everything goes fine.

ps. I have tested v1.3.1 & 1.3.. Same as v1.3.2

**Comment by EmielBruijntjes** [comment]
This is a really odd problem. The zend_next_free_module() function should just be available. Nevertheless, I will try to create a workaround.
