### ISSUE TITLE
Extension is not running under Zend Server 8

### ISSUE THREAD

**Issue by visitek** [CopernicaMarketingSoftware/PHP-CPP#187]
I have tried anything both with Examples in this repository. Ini file is loaded, but extension is not. I don't really know, if it can run under Zend Server..

**Comment by visitek** [comment]
![image](https://cloud.githubusercontent.com/assets/1741839/7197756/14535038-e4e5-11e4-958d-f70cbbfcab5a.png)

**Comment by EmielBruijntjes** [comment]
This is not a question that I can answer. I don't have Zend server, and I do not know if it works in combination with PHP-CPP.

Zend server is a closed source application isn't it? That would also make it very difficult (if not impossible) for me to fix PHP-CPP to be compatible with it.
