### ISSUE TITLE
Php::warning, Php::error are broke in nginx + phpfpm + Centos 7

### ISSUE THREAD

**Issue by hugdx** [CopernicaMarketingSoftware/PHP-CPP#190]
I am working on nginx + phpfpm + Centos 7. 

`Php::warning`, `Php::error` are broke when call in onRequest(). 

this is example:
in main.cpp

```
void init_request(){
    Php::error << "Testing" << std::flush;
}
.......
.......
extension.onRequest([]() {
    init_request();
}); 
```

**Comment by EmielBruijntjes** [comment]
What exactly do you mean with broken? Does it not compile, does it not do what it is supposed to do (generate output) or does the entire application crash?
