### ISSUE TITLE
Communication proposal: open a gitter room

### ISSUE THREAD

**Issue by Nek-** [CopernicaMarketingSoftware/PHP-CPP#191]

**Comment by EmielBruijntjes** [comment]
Would that mean that I have to chat all the time?

**Comment by annejan** [comment]
. . you are not on IRC?

You just have to idle all the time :+1:

**Comment by Nek-** [comment]
@EmielBruijntjes gitter notify by email when the chat is used.

@annejan Btw the IRC chan is not specify anywhere here, it could be cool fo have it on the readme, isn't it ?

**Comment by annejan** [comment]
Sorry for the confusion, I don't think there is an "official" IRC channel.
I would like to have one though, since I'm already idle-ing in some 60 channels, adding one won't hurt my productivity I think.

**Comment by EmielBruijntjes** [comment]
I'm going to close this one. I'm not really into chatting. If anyone wants to open a chatroom, you are free to do so, but I'm not going to join it.

**Comment by Nek-** [comment]
Well, to discuss and ask questions about the directions of the dev, I think it's a good way to explore. I think you're project is quite awesome but there is no communication at all on that :( .

**Comment by EmielBruijntjes** [comment]
You can ask such questions here. My time is limited, I am not going to add even more channels to the ones that I already have to monitor.

**Comment by Nek-** [comment]
My main question was « what about PHP 7 ? ». But you're not gonna have fun if people come here to ask question. Btw i will be happy if you answer me :-) .
