### ISSUE TITLE
Failed to compile example!

### ISSUE THREAD

**Issue by JosephP91** [CopernicaMarketingSoftware/PHP-CPP#192]
I have succesfully installed phpcpp on Ubuntu 15.04, and downloaded the example files. But when I run make command I have the following output:

g++ -Wall -c -O2 -std=c++11 -lphpcpp -fpic -o main.o main.cpp
fatal error: phpccp.h: No such file or directory

Am i missing something?

**Comment by martijnotto** [comment]
It seems the PHP-CPP library is not successfully installed, since it cannot find phpcpp.h
Are you sure you have not forgotten to execute 'make install'?

**Comment by JosephP91** [comment]
Ops, my mistake. I was writing #include "<phpccp.h>". Lol.
