### ISSUE TITLE
Syntax for exporting extensions

### ISSUE THREAD

**Issue by RicoAntonioFelix** [CopernicaMarketingSoftware/PHP-CPP#195]
What if we can clean up the syntax for exporting extensions...

By making the interface simpler for doing this work we can remove some overhead from the programmers brain from having to remember placing the extension in the data segment.

Also from unnecessary typing.

Something like the following:
```c
#include <phpcpp.h>

Php::Value multiply(Php::Parameters &params)
{
	return params[0] * params[1];
}

START_EXPORT_OF_EXTENSION("mathPlugin","1.0");

extension.add("multiply", multiply);

SUBMIT();
```

Which can be done by simply augmenting the library header with the following macros:
```c
/**
 * Macro used to add improved syntax for initializing extension exportation
 * to the php engine
 */
#define START_EXPORT_OF_EXTENSION(name, version)            \
extern "C"                                                  \
{                                                           \
	PHPCPP_EXPORT void *get_module()                        \
	{                                                       \
		static Php::Extension extension{name, version};     \

/**
 * Macro used to add improved syntax for finalizing the exportation
 */
#define SUBMIT()                                            \
		return extension;                                   \
	}                                                       \
}  
```

**Comment by EmielBruijntjes** [comment]
This is a big no-go.

I don't like the C++ preprocessor and macro's. One of the design goals of the PHP-CPP library was to get rid of all the macro's that the Zend API uses, and only use straightforward _real_ C++ code that every C++ programmer understands. If we start using macro's, we lose exactly that.

Bjarne Stroustrup also dislikes the preprocessor: http://www.stroustrup.com/bs_faq2.html#macro
