### ISSUE TITLE
Php::call with reference arguments

### ISSUE THREAD

**Issue by hugdx** [CopernicaMarketingSoftware/PHP-CPP#201]
I can't pass reference with ``Php::call``

````
Php::Array aTmpl;
aTmpl["b"] = "b_val";
aTmpl["c"] = "c_val";
aTmpl["a"] = "a_val";

Php::call("asort", aTmpl);
````
i got a error:
````
Warning: Parameter 1 to asort() expected to be a reference, value given
````
Please fix it. Thanks

**Comment by martijnotto** [comment]
Unfortunately, this is not something that is easily fixed in a way keeping the API understandable, so we won't be implementing this. This is much, much easier solved by just using the STL.
