### ISSUE TITLE
use my extension,run well in terminal but not display result on browser

### ISSUE THREAD

**Issue by barensoft** [CopernicaMarketingSoftware/PHP-CPP#207]
When I try to write my first php-cpp extension,I  had encountered an issue :use my extension,run well in terminal but not display result on browser.

my php file code is :
<code> <?php</code>
<code>echo "hello this is a test ctp extension!<br>";</code>
<code>if(function_exists("helloWorld")){</code>

<code>echo "exist\n";</code>
<code>}else{</code>
<code>echo "none exist\n";</code>
<code>}</code>
<code>echo helloWorld('baren');</code>

![issueforextension](https://cloud.githubusercontent.com/assets/11174955/8892144/4885cd74-337b-11e5-8e4c-adfefc525e4e.jpg)

my os version :centos 7  x86_64
my php version:5.4.43
my webserver :Apache/2.4.16 (Unix)

who can help me to explain it ？
thanks

**Comment by schoentoon** [comment]
Could you post the extension code please?

**Comment by barensoft** [comment]
#include <phpcpp.h>
#include<iostream>

void helloWorld (Php::Parameters &params)
{
    std::string name=params[0];
    std::cout<<"Hello "<<name<<"!"<<std::endl;

}

/**
 *  tell the compiler that the get_module is a pure C function
 */
extern "C" {
    
    /**
     *  Function that is called by PHP right after the PHP process
     *  has started, and that returns an address of an internal PHP
     *  strucure with all the details and features of your extension
     *
     *  @return void*   a pointer to an address that is understood by PHP
     */
    PHPCPP_EXPORT void *get_module() 
    {
        // static(!) Php::Extension object that should stay in memory
        // for the entire duration of the process (that's why it's static)
        static Php::Extension extension("ctpextension", "1.0");
        
        // @todo    add your own functions, classes, namespaces to the extension
           extension.add("helloWorld", helloWorld); 
        // return the extension
        return extension;
    }
}

**Comment by barensoft** [comment]
#include <phpcpp.h>
#include<iostream>

void helloWorld (Php::Parameters &params)
{
    std::string name=params[0];
    std::cout<<"Hello "<<name<<"!"<<std::endl;

}

/**
 *  tell the compiler that the get_module is a pure C function
 */
extern "C" {
    
    /**
     *  Function that is called by PHP right after the PHP process
     *  has started, and that returns an address of an internal PHP
     *  strucure with all the details and features of your extension
     *
     *  @return void*   a pointer to an address that is understood by PHP
     */
    PHPCPP_EXPORT void *get_module() 
    {
        // static(!) Php::Extension object that should stay in memory
        // for the entire duration of the process (that's why it's static)
        static Php::Extension extension("ctpextension", "1.0");
        
        // @todo    add your own functions, classes, namespaces to the extension
           extension.add("helloWorld", helloWorld); 
        // return the extension
        return extension;
    }
}

**Comment by hugdx** [comment]
try with this
````
void helloWorld (Php::Parameters &params){
	Php::out << "Hello "<<  params[0].stringValue() << "!" << std::endl;
}
````

**Comment by EmielBruijntjes** [comment]
Check this:

http://www.php-cpp.com/documentation/output-and-errors

It is better not to use "std::cout", as it will by-pass the PHP output filter and, like you've discovered, is not actually sent to the browser.

**Comment by barensoft** [comment]
Than you !schoentoon.Than you!  hugdx. Thank you ! Emiel.  I finally saw the right result.
Woo, that's really cool ---php-cpp!
![default](https://cloud.githubusercontent.com/assets/11174955/8902470/84948130-3483-11e5-95d8-78534abe3c01.png)

**Comment by Muhammad-Mubeen** [comment]
Am developing the PHP-CPP extension. When i execute the program through the cmd line then it works fine but when i run it through the browser. It does not show the output and called the functions of C++ file as undefined functions. Can anyone guide me?
