### ISSUE TITLE
How to include the third shared object(*.so) with php-cpp?

### ISSUE THREAD

**Issue by barensoft** [CopernicaMarketingSoftware/PHP-CPP#210]
Hello everyone,
I want to link  my exist shared object file (example.so), how to compile  it with php-cpp?

my mean is : I create one file: main.cpp ,in this file include  "example.h" .

 "example.h"  depend one the third shared object  example.so.

If I don't change the "makefile" anything, when I test my php-cpp extension will display error:

"php: symbol lookup error: /usr/local/php/lib/php/extensions/no-debug-non-zts-20100525/ctpextension.so: undefined symbol: _ZN15CThostFtdcMdApi15CreateFtdcMdApiEPKcbb"

how do I do ?

**Comment by EmielBruijntjes** [comment]
If you have a shared "libmyshared.so", you can link it with your extension using the "-lmyshared" flag to the linker. You can add this to the Makefile of your extension (not the PHP-CPP library).

Alternatively, you can use dlopen() to open a *.so file.

**Comment by barensoft** [comment]
thank your very much  Emiel ! I have had a success with your method!
