### ISSUE TITLE
Problems with custom class inheritance

### ISSUE THREAD

**Issue by andrej-vasilj** [CopernicaMarketingSoftware/PHP-CPP#211]
When I create a custom class PHP hierarchy in CPP, it looks like the methods are not being overrided correctly. Take a look at this minimal example:

```c++
#include <phpcpp.h>

class MyBaseClass : public Php::Base{
public:
    Php::Value doStuff(){return getValue();}
    virtual Php::Value getValue(){return "Base Class Value";}
};

class MyDerivedClass : public MyBaseClass{
public:
    Php::Value getValue() override {return "Derived Class Value";}
};

extern "C" {
    PHPCPP_EXPORT void *get_module(){
        static Php::Extension extension("issue", "1.0");
        
        Php::Class<MyBaseClass> bc("MyBaseClass");
        bc.method("doStuff", &MyBaseClass::doStuff);
       
        Php::Class<MyDerivedClass> dc("MyDerivedClass");
        dc.extends(bc);
        
        extension.add(std::move(bc));
        extension.add(std::move(dc));
                
        return extension.module();
    }
}
```

Then in PHP I execute the following code:

```php
<?php
	$derived = new \MyDerivedClass();
	echo $derived->doStuff()."\n";
?>
```

This code will print "Base Class Value" when in fact it should be printing "Derived Class Value" which is what I get if I create the same simple example in pure cpp without php extensions. Even though the cpp methods are not exposed to php, it still seems like the PHP-CPP "extends" method will somehow force the use of the base class methods.

At first I thought that maybe I could solve this by exporting the address of the function in the derived class, but not even this helps:

```c++
Php::Class<MyBaseClass> bc("MyBaseClass");
       
Php::Class<MyDerivedClass> dc("MyDerivedClass");
dc.extends(bc);
dc.method("doStuff", &MyDerivedClass::doStuff);
```

This will still print "Base Class Value"

Is this somehow desired behaviour or is it a bug? To me it seems like a bug...
Any ideas?

**Comment by schoentoon** [comment]
Sadly we'll have to re-open this issue, as the fix we provided turned out to cause some issues elsewhere.

**Comment by pwhelan** [comment]
I am utterly and totally confused... Is this fixed, partially fixed, totally broken?

**Comment by schoentoon** [comment]
@pwhelan By now it is finally fixed.

**Comment by andrej-vasilj** [comment]
At some point in September this issue was fixed, but now that I updated to the newest master branch code, the issue is unresolved once again. It is not working for me any more.
