### ISSUE TITLE
Incompatibility with libraries

### ISSUE THREAD

**Issue by jonasasx** [CopernicaMarketingSoftware/PHP-CPP#214]
When I link my extension with boost library, I have an error on runtime:

    PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/libparser-module.so' - /usr/lib/php5/20131226/libparser-module.so: undefined symbol: _ZN5boost10filesystem6detail9copy_fileERKNS0_4pathES4_NS0_11copy_optionEPNS_6system10error_codeE in Unknown on line 0

Extension is linked and compiled without any errors. What can I do?

**UPDATE:**
But when I have changed the order of linking libraries (**-lphpcpp -lboost_filesystem -ljson-c** to **-lphpcpp -ljson-c -lboost_filesystem**), this bug has disappeared.

These external libraries are independent, so they can't cause this problem.

When I use or not use some functions, the behavior of this bug changes.
For example: if I use **throw Php::Exception()**, I have this bug. But when I exclude throwing -- it's clear.

I have noticed, that tests doesn't pass:

    PHP Warning:  PHP Startup: Unable to load dynamic library '/home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so' - /home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so: undefined symbol: _ZN3PhplsERSoRKNS_8IniValueE in Unknown on line 0
    PHP Warning:  PHP Startup: Unable to load dynamic library '/home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so' - /home/ionas/make/PHP-CPP/tests/ext_dir/extfortest.so: undefined symbol: _ZN3PhplsERSoRKNS_8IniValueE in Unknown on line 0

**Comment by EmielBruijntjes** [comment]
Sometimes the order of the libraries does matter: http://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc

**Comment by jonasasx** [comment]
Ok, but why built-in tests have the same error?
