### ISSUE TITLE
In threads callbacks die with segfault.

### ISSUE THREAD

**Issue by westtrade** [CopernicaMarketingSoftware/PHP-CPP#216]
I tried to run Php::Value callbacks in `std::threads` and `boost` services. In both library if callbacks calls asynchronously in the order different from the order in which they were created i got segfault errors or "zend_mm_heap corrupted". 

If thread was joined after each threads  start, all will done normal.

**Comment by EmielBruijntjes** [comment]
I already via Disqus: http://www.php-cpp.com/documentation/lambda-functions#comment-2217627155

Better don't do that. Php variables are not necessarily thread safe. Better cast things to common C++ data types before you start using threads, or ensure that your threads complete before you return to PHP space.
