### ISSUE TITLE
Is it possible to call a method of a Php::Object or even convert it to a C++ class directly?

### ISSUE THREAD

**Issue by Frederick888** [CopernicaMarketingSoftware/PHP-CPP#223]
I was trying to make a [Bencode](https://en.wikipedia.org/wiki/Bencode) extension for PHP by [PHP-CPP](http://www.php-cpp.com/), so there were several classes like:

	class BItem : public Php::Base {
	public:
	virtual std::string getType() const {
		return "BItem";
	}
	};

	class BDict : public BItem {
	public:
	std::unordered_map<std::string, BItem*> BData;

	std::string getType() const {
		return "BDict";
	}

	Php::Value getItem(Php::Parameters &params) {
		std::string key = params[0];
		...
		...
		return Php::Object(...);
	}

	// PHP: $a = new BDict(); $b = new BDict(); $a->addItem("key", $b);
	// In fact, key itself should be a BStr but let's make it simpler in this example
	void addItem(Php::Parameters &params) {
		std::string key = params[0];

		/**
		 * Here's the part confusing me
		 * Is there something like:
		 */
		BItem *toInsert = &params[1]; // However, params[1] is actually a Php::Object
		// Or something like (assuming it's a BDict):
		std::unordered_map<std::string, BItem*> data = params[1].getData();
		BDict *toInsert = new BDict(data);
		
		BData.insert({key, toInsert});
	}
	};

	class BStr : public BItem {...};
	class BList : public BItem {...};
	class BInt : public BItem {...};

All the types except `BItem` can be inserted to a `BDict`.

So after creating an instance of one of them, how can I pass it back to the C++ part, "convert" it back to a C++ object and finally insert it into the `BData`?

Or, is there any way to access the member of the original C++ class, so that I can make a new instance?

I'm new to php extensions and any help or hint would be greatly appreciated.

**Comment by EmielBruijntjes** [comment]
Yes. If you have an object stored inside a Php::Value, and you know 100% sure that under the hood it has a C++ implementation, you can ask for this underlying C++ object:

````c++
void myFunction(Php::Parameters &params)
{
    // store the first parameter in a variable
    Php::Value object = params[0];

    // we want to be 100% sure that the passed in parameter is indeed one of our own objects
    if (!object.instanceOf("MySpecialClass")) throw Php::Exception("Wrong parameter passed");

    // cast the PHP object back into a C++ class
    MySpecialClass *cppobject = (MySpecialClass *)object.implementation();

    // @todo add your own code
}
````

Does this answer help you?

**Comment by Frederick888** [comment]
@EmielBruijntjes Thanks in advance!
