### ISSUE TITLE
Php 7 support ?

### ISSUE THREAD

**Issue by goddanao** [CopernicaMarketingSoftware/PHP-CPP#225]
Any plan for supporting php 7 ?
Some infos on https://wiki.php.net/phpng-upgrading

**Comment by ovr** [comment]
:+1:

**Comment by hylent** [comment]
:+1:

**Comment by terrywh** [comment]
any plans ?

**Comment by EmielBruijntjes** [comment]
Of course, but I first wait for stability on the PHP 7 front before I start spending time on it.

**Comment by atvise** [comment]
Current stable version of PHP 7 is 7.0.2. So have you had a look on it ? I would very appreciate it because using finally x64bit would be quite neat.

**Comment by omi-alex** [comment]
Any news is better than no news :) Thanks

**Comment by xhallix** [comment]
https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/263

so I guess this is strongly related?

**Comment by schoentoon** [comment]
We actually have PHP7 support by now. This can be found in this repository. In case you're looking for PHP-CPP please head over to https://github.com/CopernicaMarketingSoftware/PHP-CPP-LEGACY
