### ISSUE TITLE
Added support for class type Trait

### ISSUE THREAD

**Issue by gcds** [CopernicaMarketingSoftware/PHP-CPP#230]
Hello, as PHP 5.4 Supported already ended maybe, you will be including an ability to create Traits?

**Comment by gcds** [comment]
Any news?

**Comment by EmielBruijntjes** [comment]
To be honest: you are the first one who asks for it, so it does not have a lot of priority. Next stop for me is PHP7 compatibility. However, I am extremely busy at this point in time, so I do have to find time for it.

If you like to send in a pull request, I am more than happy to include it in the project (as long as it matches the coding standards and quality of the rest of the code). I don't think that it will be very complicated, as I dont expect traits to implemented in a very different way than interfaces and classes.
