### ISSUE TITLE
Properties with getter and setter methods aren't visible via Reflection

### ISSUE THREAD

**Issue by goddanao** [CopernicaMarketingSoftware/PHP-CPP#231]
I'm using a idehelper generator based on reflection to keep in sync my docs while developing my extension. I noticed that those kind of properties aren't visible by reflection, i'm missing something?

**Comment by goddanao** [comment]
Same for Magic Interfaces like ArrayAccess and Countable, are not accessible via reflection.

**Comment by martijnotto** [comment]
Are you talking about properties using __get and __set? Those aren't visible using reflection and this is not something we can fix unfortunately. It sadly doesn't work when you implement this completely in userspace either.

**Comment by goddanao** [comment]
Can the Php7 version solve this?
I'm talking about properties registered with :
...
Php::Class<ZSocket> o("ZSocket");
o.property("ipv4only", &ZSocket::get_ipv4only, &ZSocket::set_ipv4only);
o.property("type", &ZSocket::get_socket_type);

Those properties aren't available with reflection using the legacy (php 5.4+) version

**Comment by martijnotto** [comment]
This works identical in the PHP 7 version, meaning there is no reflection for these properties. I am not sure whether it is possible to make this. Perhaps it would be possible to register some form of iterator for our custom properties.

If you have the time to make this and create a pull-request I would be happy to merge it.
