### ISSUE TITLE
Problems with inheritance (see closed issue #211)

### ISSUE THREAD

**Issue by andrej-vasilj** [CopernicaMarketingSoftware/PHP-CPP#233]
Upon updating to the master code, I realized that the issue #211 is once again broken and needs fixing. I am using PHP v 5.5.9.

**Comment by martijnotto** [comment]
Please see PHP-CPP-LEGACY (since you are using PHP < 7.0). I don't believe the issue exists there now, but please feel free to open the issue there if necessary.
