### ISSUE TITLE
Array iteration corrupts existing zvals (?)

### ISSUE THREAD

**Issue by cyrus-and** [CopernicaMarketingSoftware/PHP-CPP#236]
I'm developing a PHP extension which overrides `zend_execute_*` to fetch some values from the runtime. Whenever I need to dump a value I wrap it into a `Php::Value` object then I switch over `value.type()` to properly format it. The idea is that when I find an array I want to recursively call the format function with each member. Here's the relevant part:

```c++
switch (value.type()) {
    // ...
    case Php::Type::Array:
    case Php::Type::ConstantArray:
        for (auto &it : value) {
            output_string(it.first.stringValue().c_str());
            format(it.second);
        }
        break;
    // ...
}
```

Now this works against simple test cases but when I run complex PHP code, weird things happen. Scripts complain about wrong values (e.g., NULL or unexpected types), **even if the iteration body is empty**. This suggests that zvalues may be corrupted during the mere iteration phase.

After some debugging I noticed that the problem seems to be related to [how the current value is stored][1] or to what happens when the wrapping `Php::Value` is destroyed. Any thoughts?

I apologize if I'm not providing any code to reproduce the issue but I didn't find a simple way.

[1]: https://github.com/CopernicaMarketingSoftware/PHP-CPP/blob/570590058d16274005a4994fd8f1046d0eaf7f74/zend/hashiterator.h#L228

**Comment by cyrus-and** [comment]
I don't know if this is entirely correct, but replacing the aforementioned range-based for loop with the following snippet, both formats the values properly and avoid the zvals corruption (according to some very brief testing):

```c++
#define protected public
#include <phpcpp.h>
// ...
{
    Bucket *position = nullptr;
    HashTable *table = Z_ARRVAL_P(value._val);

    zend_hash_internal_pointer_reset_ex(table, &position);

    for (;;) {
        // fetch key
        Php::Value key;
        zend_hash_get_current_key_zval_ex(table, key._val, &position);
        if (Z_TYPE_P(key._val) == IS_NULL) {
            break;
        }
        // fetch value
        zval **value;
        zend_hash_get_current_data_ex(table, (void **)&value, &position);
        // consume
        output_string(key.stringValue().c_str());
        format(Php::Value(*value));
        // next
        assert(zend_hash_move_forward_ex(table, &position) == SUCCESS);
    }
}
```

As you can see I just copied the relevant parts from the `HashIterator` class, the only real difference is that the fetched values are not *placed* into the pair, rather they are consumed immediately (within the same block).

**Comment by cyrus-and** [comment]
Browsing the existing issues and PRs, I've found #115 by @andot; among the other things that PR highlights a problem with the [move operator][1] which looks the same I'm reporting here. The proposed solution (andot/PHP-CPP@cada2bd8d969fdfe1ebc4abcfa5b52e56eca7bcf) happens to fix this issue.

@andot why does that commit has never been merged with this repo?

[1]: /CopernicaMarketingSoftware/PHP-CPP/pull/115#issuecomment-48591931
[2]: andot/PHP-CPP@cada2bd8d969fdfe1ebc4abcfa5b52e56eca7bcf

**Comment by martijnotto** [comment]
I believe this issue is fixed in the latest commit to PHP-CPP. I experienced the same problem and after changing the move constructor of Php::Value it seems to be solved. If you still experience this problem, please reopen the issue and we'll see what we can do about it.

**Comment by cyrus-and** [comment]
@martijnotto Actually I'm no more able to compile this library, it seems that 9f2e816c787c30ceeb139623c8dae594c4b4443d broke something, at least on my setup: `php5-dev` Debian package version `5.6.20`.

```
In file included from zend/includes.h:130:0,
                 from zend/inivalue.cpp:8:
zend/constantimpl.h:85:50: error: macro "ZVAL_STRINGL" requires 4 arguments, but only 3 given
         ZVAL_STRINGL(&_constant.value, value, len);
                                                  ^
[...]
```

**Comment by schoentoon** [comment]
@cyrus-and That's entirely correct, this repository now (master at least) is now for PHP7. For PHP5 please use https://github.com/CopernicaMarketingSoftware/PHP-CPP-LEGACY instead.

**Comment by cyrus-and** [comment]
Oh, thank you @schoentoon, didn't know it.
