### ISSUE TITLE
error: ‘Parameters’ is not a member of ‘Php’

### ISSUE THREAD

**Issue by Jayad** [CopernicaMarketingSoftware/PHP-CPP#241]
Hi ,
I am in centos with g++ 4.7.2 version.
getting the following error 

/opt/centos/devtoolset-1.1/root/usr/bin/g++  -Wall -c -O2 -std=c++11 -fpic -o main.o main.cpp 
main.cpp:13:15: error: ‘Parameters’ is not a member of ‘Php’
main.cpp:13:32: error: ‘params’ was not declared in this scope
main.cpp:14:1: error: expected ‘,’ or ‘;’ before ‘{’ token
make: *** [main.o] Error 1

**Comment by schoentoon** [comment]
Could you post your main.cpp please?

**Comment by Jayad** [comment]
int bioMatch (Php::Parameters &params)
{
    long err;
    LPSGFPM sgfplib = NULL;
      BYTE *ansiMinutiaeBuffer1;
  BYTE *ansiMinutiaeBuffer2;
        BOOL matched;

          DWORD image_width = 260;
  DWORD image_height = 300;
  DWORD image_dpi = 500;
   std::string name=params[0];
   std::string name1=params[1];

   std::cout<<"First param"<< params[0]<<"!"<<std::endl;
    std::cout<<"Second param"<< params[1]<<"!"<<std::endl;
ansiMinutiaeBuffer1=(BYTE*) malloc(800);
ansiMinutiaeBuffer2=(BYTE*) malloc(800);
        memcpy(ansiMinutiaeBuffer1, params[0], 800);
 memcpy(ansiMinutiaeBuffer2, params[1], 800);

      if (matched == true)
                {
            std::cout << "Pattern Matched " <<std::endl;
//              return 0;
                }
        else
                {
            std::cout << "No Pattern Matched " <<std::endl;
//       return 1;
                }
        }

}

extern "C" {

    /**
     *  Function that is called by PHP right after the PHP process
     *  has started, and that returns an address of an internal PHP
     *  strucure with all the details and features of your extension
     *
     *  @return void*   a pointer to an address that is understood by PHP
     */
    PHPCPP_EXPORT void *get_module()
    {
        // static(!) Php::Extension object that should stay in memory
        // for the entire duration of the process (that's why it's static)
//        static Php::Extension extension("libsgfdu05", "1.0");
     //static Php::Extension extension("libsgfplib", "1.0");
     static Php::Extension extension("jdbio", "1.0");
        extension.add("bioMatch", bioMatch, {
                        Php::ByRef("a", Php::Type::String),
                        Php::ByRef("b", Php::Type::String)
        });
        // @todo    add your own functions, classes, namespaces to the extension

        // return the extension
        return extension;
    //    return (void*) 1; //extension;
    }
}

**Comment by schoentoon** [comment]
I don't see a clear reason why this shouldn't work right away, assuming you did include phpcpp.h of course. Besides that your bioMatch function has to return a Php::Value, otherwise you won't be able to add it to the extension.

**Comment by Jayad** [comment]
Added return type also, 
Php::Value bioMatch (Php::Parameters &params)
{
    long err;
    LPSG

....
}

Any thing else i am missing?

**Comment by schoentoon** [comment]
Besides I don't see anything missing besides #include <phpcpp.h>

**Comment by martijnotto** [comment]
Since I don't see any #include directive in your comment, I am going to assume that you forgot to #include <phpcpp.h>

If this is not the case please post the complete code that fails to compile and reopen this issue.

**Comment by hugdx** [comment]
Please see on [https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/209#issuecomment-160229494](https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/209#issuecomment-160229494)
