### ISSUE TITLE
Can create a custom sessions handler ?

### ISSUE THREAD

**Issue by Ducatel** [CopernicaMarketingSoftware/PHP-CPP#242]
Hi everybody,

I'm new with PHP-CPP and I'm trying to find a way to implement a custom session handler.
Is it possible with PHP-CPP ? (Session handler seems to be in C not in C++)

Thanks for your help

**Comment by martijnotto** [comment]
We have not made any special functionality to override the session handlers in PHP-CPP. Your best bet is to either use the functions available in PHP userland (functions like session_set_save_handler) which you can execute using Php::call. The alternative is to see if you could add it to PHP-CPP yourself. I'd be interested in merging a pull-request if you could provide one.
