### ISSUE TITLE
PHP-CPP v2.0 MacOS GCC compile problem. PHP version is 7.0.7

### ISSUE THREAD

**Issue by furkankirac** [CopernicaMarketingSoftware/PHP-CPP#244]
Compiling PHP-CPP v2.0 with GCC 6.1.0_0 produces below compile error:
zend/classimpl.cpp: In member function 'zend_object_handlers* Php::ClassImpl::objectHandlers()':
zend/classimpl.cpp:344:32: error: invalid conversion from 'int (*)(zval*, long int*) {aka int (*)(_zval_struct*, long int*)}' to 'zend_object_count_elements_t {aka int (*)(_zval_struct*, long long int*)}' [-fpermissive]
     _handlers.count_elements = &ClassImpl::countElements;

**Comment by martijnotto** [comment]
Are you running on a 32-bit OS? I see that PHP defines their 'zend_long' type differently for 32-bit since PHP 7.0, which seems to be the issue you are running into.

This is now solved, but you may encounter other issues similar to this. Please feel free to re-open the issue should you encounter similar problems compiling.

**Comment by furkankirac** [comment]
OS is definitely 64bit. MacOS ElCapitan 10.11.5 (latest as of now). Maybe PHP is 32bit? How can I understand?
php -v output is:
PHP 7.0.7 (cli) (built: May 30 2016 11:51:20) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

Previous errors are solved but now below compilation error is given:
zend/value.cpp: In member function 'int Php::Value::size() const':
zend/value.cpp:1235:55: error: invalid conversion from 'long int*' to 'zend_long* {aka long long int*}' [-fpermissive]
         return Z_OBJ_HT_P(_val)->count_elements(_val, &result TSRMLS_CC) == SUCCESS ? result : 0;

**Comment by martijnotto** [comment]
I missed the part about OS X. They must just have different type definitions. I updated value.cpp to deal with this, but as said, there may be more places where this goes wrong - and I don't have a Mac here to test this.

I do not know if the 'make' utility provided with OS X supports the -k option, if it does please use it. If a compile error occurs it will just continue compiling other stuff so we know what else is broken. This way we don't have to have a back-and-forth for every small error.

**Comment by furkankirac** [comment]
I had already used the -k switch and found out that this one was the last small error.
Now it compiles. But since its MacOS I had to make a few changes in the makefile that are already documented.
Thanks a lot Martijn. Regards.
