### ISSUE TITLE
PHP-CPP v2.0: __construct not working.

### ISSUE THREAD

**Issue by furkankirac** [CopernicaMarketingSoftware/PHP-CPP#245]
I switched my project to PHP7+PHP-CPP2.0. Previously working Php::Class now gives an error when working in run-time.
Class is something like this:
```
    class PhpListeTek : public Php::Base
    {
    public:
        PhpListeTek() {}
        virtual ~PhpListeTek() {}
        void __construct(Php::Parameters &params);
    };

```

Object has a few attributes (tn, kod, anh, baslik) that are constructed in __construct as below:
```
void PhpListeTek::__construct(Php::Parameters &params)
{
    auto &L = listeler();
    int listetn = params[0];

    Liste &l = L[listetn];
    Php::Value self(this);
    self["tn"] = l.tn;
    self["kod"] = l.kod;
    self["anh"] = l.anh;
    self["baslik"] = l.basliklar[langId(params[1])];
}

```

Class is added to the extension as below:
```
    static Php::Extension ext("libeis", "1.0");
    Php::Class<PhpListeTek> listetek("ListeTek");
    listetek.method<&PhpListeTek::__construct>("__construct", { Php::ByVal("listetn", Php::Type::Numeric), Php::ByVal("dil", Php::Type::String) });
    ext.add(std::move(listetek));
```

When I watch the attributes of the PHP side object, there is none. I call the PHP-CPP liste function as below (akDersTuru is a constant.).
```
$A = liste(akDersTuru, $_SESSION["dil"]);
```
Accessing any attribute of $A such as:
```
$A->tn
```
gives an error:
```
Notice: Undefined property: ListeTek::$tn in ...
```
When I var_dump $A variable, there is no created attributes.
Am I missing something? This was working in PHP-CPP v1.5.3.
Regards.

**Comment by martijnotto** [comment]
I think you are missing something. I cannot reproduce your issue. I have created the following test-case based on your issue:

```c++
#include <phpcpp.h>

class PhpListeTek : public Php::Base
{
public:
    PhpListeTek() = default;
    virtual ~PhpListeTek() = default;
    void __construct(Php::Parameters &params)
    {
        Php::Value self(this);
        self["tn"] = 10;
        self["kod"] = "100";
        self["anh"] = "bla";
        self["baslik"] = "no thanks";
    }
};

extern "C" {

    PHPCPP_EXPORT void *get_module()
    {
        static Php::Extension extension{ "Listetek", "1.0" };

        Php::Class<PhpListeTek> listetek{ "ListeTek" };

        listetek.method<&PhpListeTek::__construct>("__construct");

        extension.add(std::move(listetek));
        return extension;
    }

}
```

If I then create an instance of 'ListeTek' from PHP I can see those properties. I don't really see a bug in your code, so it's likely somewhere in the code you did not publish. If you can't figure it out, please post the complete code, perhaps I can spot the bug.

**Comment by furkankirac** [comment]
Hi Martijn,
I worked on your example as well. And it works as you suggested. What doesn't work is below code. I added a new liste_ function which creates a ListeTek instance in C++ side by using Php::Object. Returning Php::Object does not work well in Php side:
```
Php::Value liste_(Php::Parameters &params)
{
    int tn = params[0];
    std::string dil = params[1].stringValue();
    Php::Value A = Php::Object("ListeTek", tn, dil);
    return A;
}
```
Now calling liste_ from Php side as below does not work:
```
        $a = liste_($tn, $dil);
        var_dump($a);
```
$a is empty in this case. However when I create it from the Php side using `$a = new ListeTek($tn, $dil)` it works and $a is populated.

Hope that I could clarify the problem.
Regards.

**Comment by martijnotto** [comment]
This seems to be a bug. The problem originates in Object.cpp in the call to zend_hash_exists, which always returns 0 - even though the key __construct exists within the HashTable. I will see if this is a bug in PHP or if there is some hidden step we're missing.

Should it be possible to construct this class directly from PHP or do you intend to only allow constructing it from a helper function (like the liste_ function you show here)? In that case a good workaround is to move the initialisation to the real constructor, remove the whole __construct method and then do something like:

```c++
return Php::Object("ListeTek", new ListeTek{ tn, dil });
```
