### ISSUE TITLE
Version 2 to come soon?

### ISSUE THREAD

**Issue by patlecat** [CopernicaMarketingSoftware/PHP-CPP#246]
I downloaded version 1.5.3 and found that it has the version 1.5.2 in the makefile.... and then I saw something about version 2 in the commits. But what will change in V2 and when can we expect it?

Another question: Do I not need to compile PHP before using PHP-Cpp? There is no word about that in your documentation.

**Comment by schoentoon** [comment]
PHP-CPP version 2 (this repository) is for PHP7 that's the big change really. For PHP-CPP with PHP5 support please use https://github.com/CopernicaMarketingSoftware/PHP-CPP-LEGACY instead.

And no, you do not need to compile PHP. You simply need the header files for php, which are usually provided by your Linux distribution as some development package. Like php-dev on Ubuntu or php-devel on Fedora, etc.

**Comment by patlecat** [comment]
Okay sounds good, if you could document that part with the PHP header files.

So actually the version 1.5.3 (or 1.5.2 as its called) is already working with PHP7? What has changed with PHP7 in the API?

**Comment by schoentoon** [comment]
That is correct, current master is working with PHP7. Api wise not much has changed and your old PHP-CPP extension should just work fine.

**Comment by patlecat** [comment]
Still won't answer my question what changed... ;) And why you then warn people to only use it with PHP7 henceforth...?

**Comment by schoentoon** [comment]
This repository will simply no longer compile at all with PHP5 due to too many internal changes in PHP7.
