### ISSUE TITLE
Trying to build extension on Redhat Linux 6

### ISSUE THREAD

**Issue by rohan-shimpi** [CopernicaMarketingSoftware/PHP-CPP#250]
I am trying to write a new CPP extension and have to run it on Redhat Linux 6. But facing issues due to the gcc version which is 4.4.7. 
Running PHP-CPP requires stdc++11 which is available for version gcc 4.7 and above.
How do I proceed with this. Is there any documentation that I can follow?

Regards.

**Comment by schoentoon** [comment]
You'll need a more up to date compiler. According to [this stackoverflow topic](https://stackoverflow.com/questions/9811587/how-to-install-c11-c0x-header-files-on-redhat-enterprise) that I found by quickly searching for "Red Hat 6 C++11". The Red Hat Developer Toolset should do the trick, I recommend you to look into that.
