### ISSUE TITLE
Can't push my local changes in repository

### ISSUE THREAD

**Issue by maj0** [CopernicaMarketingSoftware/PHP-CPP#251]
When I try to call git push, git prompt for username & password and I provide info but get following error
remote: Permission to CopernicaMarketingSoftware/PHP-CPP.git denied to maj0.
fatal: unable to access 'https://github.com/CopernicaMarketingSoftware/PHP-CPP.git/': The requested URL returned error: 403

Regards.
maj0

**Comment by schoentoon** [comment]
This is quite normal as you simply don't have write access to our repository. I recommend you make a fork of the project and push your changes there. You can then make a pull request with your changes to us. For more info, please check this documentation from github https://help.github.com/articles/fork-a-repo/ https://help.github.com/articles/using-pull-requests/
