### ISSUE TITLE
Compiling on OSX

### ISSUE THREAD

**Issue by rbakels** [CopernicaMarketingSoftware/PHP-CPP#26]
Hi there,

I've managed to get PHP-CPP compiling and linking on OSX (10.9.2) targeting PHP5.5. Because it uses clang on OSX by default, there were some issues to be resolved with both compilation and linking. The Makefile is changed as well.

I will open a pull request tomorrow while I review and clean some things. This is just a heads up, so you'll know it is working. I cannot test is on Linux, since I don't have access to a Linux machine for now, so I don't know how GCC behaves on the changes. I;m fearing it will break the build.

Tomorrow I can access a Linux machine at work, so I can test it myself before opening a pull request, if it's desired.

Thanks!

**Comment by yuriteixeira** [comment]
`-install_name` was needed in php-cpp task, for Mac OS X El Capitan (10.11.6)
