### ISSUE TITLE
Cannot access to protected propertirs

### ISSUE THREAD

**Issue by kandy** [CopernicaMarketingSoftware/PHP-CPP#260]
I use code from  http://www.php-cpp.com/documentation/properties
like  

```
 virtual void __construct(Php::Parameters &params)
    {
        // get self reference as Php::Value object
        Php::Value self(this);
        Php::Value data = params[0];

        // initialize a public property
        self["property1"] = data;
    }
```

but define property as protected `example.property("property1", "xyz", Php::Protected);`
 and call as `new ObjectProto([])` in php code  and I got
PHP Fatal error:  Uncaught Error: Cannot access protected property ObjectProto::$property1 in /vagrant/PHP-CPP/Examples/simple/simple.php:4

**Comment by vstepanyuk** [comment]
+1

**Comment by sjinks** [comment]
#288 should help :-)
