### ISSUE TITLE
Extension not working on lampp server

### ISSUE THREAD

**Issue by arshidkv12** [CopernicaMarketingSoftware/PHP-CPP#267]
I created test extension. It is working on php cli. But not working on lampp server.

OS: Ubuntu
PHP5

**Comment by arshidkv12** [comment]
I edited php.ini file. Then I got following error.

 PHP Startup: Unable to load dynamic library '/opt/lampp/lib/php/extensions/no-debug-non-zts-20131226/ttarshid.so' - /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /opt/lampp/lib/php/extensions/no-debug-non-zts-20131226/ttarshid.so) in Unknown on line 0

**Comment by terrywh** [comment]
I think the problem is that you build the extension on one server who has a newer version of libstdc++ and copied that compiled extension to another server who does not have the specific version

**Comment by martijnotto** [comment]
For PHP 5 you should be using PHP-CPP-LEGACY. Ideally you want to build on the same server that you run it on.
