### ISSUE TITLE
 'byRef' is not a member of 'Php'

### ISSUE THREAD

**Issue by DRogue1337** [CopernicaMarketingSoftware/PHP-CPP#270]
This is what I get when I do "make" on MacOS 10.11.6.

```
main.cpp: In function 'void* get_module()':
main.cpp:29:17: error: 'byRef' is not a member of 'Php'
                 Php::byRef("array", Php::Type::Array, true),
                 ^~~
main.cpp:30:17: error: 'byVal' is not a member of 'Php'
                 Php::byVal("path", Php::Type::String, true),
                 ^~~
main.cpp:31:17: error: 'byVal' is not a member of 'Php'
                 Php::byVal("value", Php::Type::String, true)
```

I tried recompiling the whole thing because I had issues while installing the first time. I did the steps as described here: https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/255
I checked if the necessary files are included but I keep getting this error.

// EDIT:

Ok. I'm getting the exact same error/s on Ubuntu 16.04. I guess I took a wrong turn somewhere.

**Comment by terrywh** [comment]
I think it's 'ByRef'

**Comment by martijnotto** [comment]
As @terrywh correctly answered, the correct names are Php::ByVal and Php::ByRef
