### ISSUE TITLE
Property with default value

### ISSUE THREAD

**Issue by vstepanyuk** [CopernicaMarketingSoftware/PHP-CPP#277]
How can I define property with default value array(); ?
```

class ClassName {
  protected $propertyName = [];
}
```

Thx

**Comment by sjinks** [comment]
Zend API [does not support this](http://lxr.php.net/source/xref/PHP-7.0/Zend/zend_API.c#3657) — default property values cannot be arrays, objects or resources.

I would suggest you to set the property value to `null` and handle that case in your code (say, create an empty array).
