### ISSUE TITLE
Makefile with mixture of C and C++ code

### ISSUE THREAD

**Issue by ond1** [CopernicaMarketingSoftware/PHP-CPP#295]
Hi,

I have a project with a mixture of C and C++ code. How can I get your example Makefile to work with the both together. I managed to use it with the C++ code base but struggling to get the C code to compile. Any tips or example Makefile to compile a directory which contains both C and C++ code please.

**Comment by sjinks** [comment]
You will probably need rules like this:

```Make
%.o: %.c
        $(CC) $(CPPFLAGS)  $(CFLAGS) -c "$<" -o "$@"

%.o: %.cpp
        $(CXX) $(CPPFLAGS)  $(CXXFLAGS) -c "$<" -o "$@"
```

**Comment by sjinks** [comment]
Please note that there should be a tab, not 8 spaces in the rules.

**Comment by ond1** [comment]
Thanks for your help.

In the example supplied from php_cpp (see below). It works with just cpp files and builds the library. Not sure how to extend this to include c files and do the linkage building of the library. I tried many things:

SOURCES				=	$(wildcard *.cpp)
OBJECTS				=	$(SOURCES:%.c%=%.o)

all:					${OBJECTS} ${EXTENSION}

${EXTENSION}:			${OBJECTS}
						${LINKER} ${LINKER_FLAGS} -o $@ ${OBJECTS} ${LINKER_DEPENDENCIES}

${OBJECTS}:
						${COMPILER} ${COMPILER_FLAGS} $@ ${@:%.o=%.cpp}

install:		
						${CP} ${EXTENSION} ${EXTENSION_DIR}
						${CP} ${INI} ${INI_DIR}

**Comment by sjinks** [comment]
Something like this:

```Makefile
EXTENSION = sample.so
EXTENSION_DIR = $(shell php-config --extension-dir)
INI_DIR = <your path here>
INI = <ini file name here>
PHP_LDFLAGS = -shared $(shell php-config --ldflags)
LDLIBS = -lphpcpp

CXX_SOURCES = $(wildcard *.cpp)
C_SOURCES = $(wildcard *.c)
CXX_OBJECTS = $(patsubst %.cpp,%.o,$(CXX_SOURCES))
C_OBJECTS = $(patsubst %.c,%.o,$(C_SOURCES))

all: $(EXTENSION)

$(EXTENSION): $(CXX_OBJECTS) $(C_OBJECTS)
        $(CXX) $^ $(PHP_LDFLAGS) $(LDFLAGS) $(LDLIBS) -o "$@"

%.o: %.c
        $(CC) $(CPPFLAGS) $(CFLAGS) -c "$<" -o "$@"

%.o: %.cpp
        $(CXX) $(CPPFLAGS) $(CXXFLAGS) -c "$<" -o "$@"

install:
        cp -f "$(EXTENSION)" "$(EXTENSION_DIR)"
        cp -f "$(INI)" "$(INI_DIR)"

clean:
        -rm -f $(EXTENSION) $(CXX_OBJECTS) $(C_OBJECTS)
```

If this does not work for you as expected, please create a test repo, I will look at it and tell you what is wrong :-)

**Comment by ond1** [comment]
Thanks for your help. It has worked perfectly.

**Comment by sjinks** [comment]
Cool! :+1:

**Comment by martijnotto** [comment]
The question appears to be solved.
