### ISSUE TITLE
Throw custom exception class

### ISSUE THREAD

**Issue by AndreasHeiberg** [CopernicaMarketingSoftware/PHP-CPP#315]
I would like to be able to throw an custom exceptions to make it clear what is being caught.

I tried creating and throwing an extension of Php::Exception:

```
class CustomException : public Php::Exception {};
```

but this gives me `no matching conversion for functional-style cast from 'const char *' to 'ParserException'` at compile time.

I found one issue (#275) discussing this in 2014, but not a solution.

Is it possible to throw custom exception?

**Comment by EmielBruijntjes** [comment]
This is currently not possible

**Comment by AndreasHeiberg** [comment]
Is there any work to make this doable?

Is there anything I can do?

**Comment by sjinks** [comment]
@AndreasHeiberg do you want to throw an exception in C++ and catch it in PHP? Or what exactly are you trying to achieve?

**Comment by AndreasHeiberg** [comment]
Yes I would like to throw an exception in my extension and catch it in PHP. That would require me to register a PHP class that extends \Exception in my PHP extension and then throw it from said extension.

In PHP I want something like:

```
try {
    function_from_my_extension();
}
catch (\MyExtension\Exceptions\CustomOne $e) {
    // something appropriate 
}
catch (\MyExtension\Exceptions\CustomTwo $e) {
    // something appropriate 
}
```

**Comment by sjinks** [comment]
Well, if you don't mind having some low level code…

```c++
#include <Zend/zend.h>
#include <Zend/zend_exceptions.h>

// global
zend_class_entry* my_exception_ce;

// ...

extension.onStartup([]() {
    zend_class_entry ce;
    INIT_CLASS_ENTRY(ce, "MyExtension\\Exceptions\\CustomOne", NULL);
    my_exception_ce = zend_register_internal_class_ex(&ce, zend_exception_get_default(), NULL);
});

// Your function
void my_function()
{
    zend_throw_exception_ex(my_exception_ce, 0, "Something bad has happened in %s on line %d", __FILE__, __LINE__);
}
```

**Comment by sjinks** [comment]
if you need to interrupt your C++ code, you will probably need to 

```c++
throw Php::Exception("...");
```

right after `zend_throw_exception_ex`.

**Comment by mdumitrean** [comment]
Hmm.... I think this is what you wanted:
Here's the custom PHP Exception I want to throw:
```php
    class CdtException extends Exception {
    	public function __construct($context, $line, $message, $destination = 'cdt-error_log', $code = 0, Exception $previous = null) {
    		parent::__construct(sprintf("[%s/%d] %s", gettype($context) == 'object' ? get_class($context) : $context, $line, $message), $code, $previous);
    		error_log
    		(
    				// Message
    				sprintf("[%s] %s\n", gettype($context) == 'object' ? get_class($context) : $context, $message),
    				// Append to destination
    				3,
    				$destination
    		);
		}
		
		static function createCdtException($file, $line, $message) {
			throw new CdtException($file, $line, $message);
		}
    }
```

Here is my CPP code (a light wrapper around the real Php CdtException):
```c++
class CdtException : public Php::Base {
private:
public:
	CdtException(std::string file, uint64_t line, std::string message) {
		Php::Value ex("CdtException::createCdtException");
		ex(file,int2str(line),message);
	}
};
```

Then here's me throwing an exception in CPP:
```c++
	new CdtException(__FILE__, (uint64_t)__LINE__, "Error creating object");
```
Here is the output from command line:
```
PHP Fatal error:  Uncaught exception 'CdtException' with message '[ComponentManager.cpp/121] Error creating object' in /Library/WebServer/Documents/cdtweb/model/helper_objects/Exceptions.php:64
```
My stack is obviously catching the exception:
```json
{
    "status": "error",
    "data": "",
    "message": "[ComponentManager.cpp/116] Error creating object"
}
```

Did I miss something?  This seems to work.

**Comment by sandrokeil** [comment]
@EmielBruijntjes Any plans to support own exception and PHP SPL exception classes? I found that there was a [PR](https://github.com/CopernicaMarketingSoftware/PHP-CPP/pull/9) with commit https://github.com/CopernicaMarketingSoftware/PHP-CPP/pull/9/commits/48d706f60a3900b04366e561ee1a76a1c5be5036 that adds the support. It should be implemented in [origexception.h](https://github.com/CopernicaMarketingSoftware/PHP-CPP/blob/e7807cf1b48c451bd05e81d78268152bdfb756db/zend/origexception.h#L180) right? The examples above doesn't worked for me. I'm new to c++. 

/cc @Photonios
