### ISSUE TITLE
[Question][Would Implement][Guidance] OpenCV and image data passing through PHP-CPP

### ISSUE THREAD

**Issue by piotroxp** [CopernicaMarketingSoftware/PHP-CPP#336]
Hello Dear Community, it is my first post. I'm sorry for any inconvienience.

I'm implementing a funny thing in PHPCPP (AI online image recognizer using raw dlib and mathematics because I enjoy it) and found out that the best way to go for my particular application is to use opencv mat objects. The questions to you guys are:

- is any image backend available in PHP-CPP?
- if not, how would I go about adding a custom passable type that would suit my needs? I can share them later on
- is it pointless? Serious question - if you know of better methods to pass images PHP<->C++ I would gladly appreciate any input.

Otherwise, thank you for your fantastic work - if I ever earn money out of whatever I build with phpcpp, you will receive a fat check from it. Thank you guys and keep up the magnificent work!

**Comment by EmielBruijntjes** [comment]
- No. PHP-CPP is a layer on top of the PHP C API to make programming easier. It does not contain code to process or manipulate images (although you can make calls back into PHP space that does have all sort of image handling functions).
- The thing that you are doing sounds correct. You can use PHP-CPP in combination with other libraries to do this. You do not have to share anything if you don't want.
- It does not sound pointless to me.
