### ISSUE TITLE
does anybody compile php-cpp success in windows?

### ISSUE THREAD

**Issue by gouchaoer** [CopernicaMarketingSoftware/PHP-CPP#337]
I need to make my extension work on both linux and windows.
But the maintainer is not interested in supporting windows.
So does anyone tried that?

**Comment by atvise** [comment]
Currently I have it compiled under Win10 x64bit PHP 7.1.4 with CMake and conan (it's not neccessary but makes everything easier for cross compiling and reusing it for multiple projects) files as a static library only in Release or RelWithDebInfo. One problem I currently can't solve for Debug builds are following link errors:

``
6>phpcpp.lib(value.obj) : error LNK2019: unresolved external symbol __imp__emalloc@@8 referenced in function "struct _zend_string * __cdecl zend_string_alloc(unsigned __int64,int)" (?zend_string_alloc@@YAPEAU_zend_string@@_KH@Z)
6>phpcpp.lib(classimpl.obj) : error LNK2001: unresolved external symbol __imp__emalloc@@8
6>phpcpp.lib(extensionimpl.obj) : error LNK2001: unresolved external symbol __imp__emalloc@@8
6>phpcpp.lib(value.obj) : error LNK2019: unresolved external symbol __imp__efree@@8 referenced in function "void __cdecl zend_string_release(struct _zend_string *)" (?zend_string_release@@YAXPEAU_zend_string@@@Z)
6>phpcpp.lib(classimpl.obj) : error LNK2001: unresolved external symbol __imp__efree@@8
6>phpcpp.lib(script.obj) : error LNK2001: unresolved external symbol __imp__efree@@8
6>phpcpp.lib(file.obj) : error LNK2001: unresolved external symbol __imp__efree@@8
6>phpcpp.lib(value.obj) : error LNK2019: unresolved external symbol __imp__zval_dtor_func@@8 referenced in function _zval_ptr_dtor_nogc
6>phpcpp.lib(value.obj) : error LNK2019: unresolved external symbol __imp__zval_copy_ctor_func@@8 referenced in function "public: __cdecl Php::Value::Value(struct _zval_struct *,bool)" (??0Value@Php@@QEAA@PEAU_zval_struct@@_N@Z)
6>phpcpp.lib(classimpl.obj) : error LNK2001: unresolved external symbol __imp__zval_copy_ctor_func@@8
6>phpcpp.lib(value.obj) : error LNK2019: unresolved external symbol __imp__convert_to_string@@8 referenced in function "public: virtual class Php::Value & __cdecl Php::Value::setType(enum Php::Type)& " (?setType@Value@Php@@UEGAAAEAV12@W4Type@2@@Z)
6>phpcpp.lib(classimpl.obj) : error LNK2019: unresolved external symbol __imp__ecalloc@@16 referenced in function "public: __cdecl Php::ObjectImpl::ObjectImpl(struct _zend_class_entry *,class Php::Base *,struct _zend_object_handlers *,int)" (??0ObjectImpl@Php@@QEAA@PEAU_zend_class_entry@@PEAVBase@1@PEAU_zend_object_handlers@@H@Z)
6>phpcpp.lib(classimpl.obj) : error LNK2019: unresolved external symbol __imp__estrndup@@16 referenced in function "public: static int __cdecl Php::ClassImpl::serialize(struct _zval_struct *,unsigned char * *,unsigned __int64 *,struct _zend_serialize_data *)" (?serialize@ClassImpl@Php@@SAHPEAU_zval_struct@@PEAPEAEPEA_KPEAU_zend_serialize_data@@@Z)
6>C:\Program Files (x86)\Windows Kits\8.0\Lib\win8\um\x86\odbc32.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
``

But if you fine with Release or RelWithDebInfo builds I can somehow list the details of compiling it.

**Comment by weltling** [comment]
@atvise could you please share your cmake scripts?

Thanks.

**Comment by fifothekid** [comment]
@atvise where can I find the cmake branch?

**Comment by mvdwerve** [comment]
Going to close this now, as the CMake file has been merged.
