### ISSUE TITLE
Multiple cpp files

### ISSUE THREAD

**Issue by gnat42** [CopernicaMarketingSoftware/PHP-CPP#354]
So this is probably a simple problem however it's been around 20 years since I've worked with c/c++ so can't seem to solve this.

I wanted to split some of my classes so created two .h files and two .cpp files. I thought I was doing it correctly, it compiles successfully. However the extension can't be loaded because of an undefined symbol which matches the class name.

I couldn't find anything in the docs about what I was doing wrong, I'm sure its probably simple c/c++ but can't find anything. 

Help?

**Comment by gnat42** [comment]
nvm - fixed...

**Comment by gtamas** [comment]
@gnat42 
I'm experiencing the exact same problem. What was the solution?

One of my classes is undefined symbol now. But this worked fine when there was only main.cpp.

**Comment by gnat42** [comment]
Hello,
  Sorry to hear that - I actually don't know how I fixed it because it wasn't included in a commit message anywhere. My first commit in the project this refers to is Oct 31, 2017 which is the date I posted my problem. However here are my *current* Makefile and main.cpp.

Hope it helps. More than likely the issue is how the object files are being linked into the resulting library .so file.


[Makefile.txt](https://github.com/CopernicaMarketingSoftware/PHP-CPP/files/5575305/Makefile.txt)
[main.cpp.txt](https://github.com/CopernicaMarketingSoftware/PHP-CPP/files/5575306/main.cpp.txt)

**Comment by gtamas** [comment]
@gnat42 @EmielBruijntjes 

Thanks for the info.

Unfortunately I'm still struggling with this. Our linker calls are exactly the same, but the compiler call seems to be different

Compiler:

`g++ -Wall -I/path/to/aspose-slides-cpp-linux-20.10/include/aspose.slides.cpp -I/path/to/aspose-slides-cpp-linux-20.10/include/asposecpplib -c -O2 -std=c++14 -fpic -o src/aspose_util.o src/aspose_util.cpp`

Linker:

`g++ -shared -fuse-ld=gold -o build/aspose_php.so src/aspose_util.o src/main.o -lstdc++ -lphpcpp -lAspose.Slides_clang3_libstdcpp -laspose_cpp_clang3_libstdcpp -L/path/to/aspose-slides-cpp-linux-20.10/lib`

What's wrong with this? The class is public by default, right? I don't specify any flags. This is all I do in main.cpp:
```
        Php::Class<AsposeUtil> util("AsposeUtil");
        Php::Namespace ns("AsposePhp");
        util.method<&AsposeUtil::getVersion>("getVersion", Php::Static, {});
        ns.add<AsposeUtil>("AsposePoseUtil");
        extension.add(std::move(ns));

```
What's wrong?? Don't get it...

The linker clearly adds aspose_util.o, which contains a class, yes this class is undefined symbol when I load the extension with PHP.

Any ideas?

**Comment by gtamas** [comment]
@EmielBruijntjes 

How can I make a class visible to PHP? It doesn't matter which class I try, I always get this error "undefined syumbol" error. 
These classes are defined in their own .h files and they are implemented in separate .cpp files. So there is a .h / .cpp for each class. 
But this all worked fine when there was only a main.cpp

Unfortunately my C knowledge is limited. What could be wrong here?

**Comment by gtamas** [comment]
@gnat42 

Solved.. 
I declared the constructor / desctructor in .h files but forgot to init them. Now everything works.
Thanks for the help!
