### ISSUE TITLE
segfault when throwing exceptions

### ISSUE THREAD

**Issue by gnat42** [CopernicaMarketingSoftware/PHP-CPP#365]
Hello,

  I'm not sure why but I have an extension that was working great. As I try to add a new feature, anyplace/time I throw an exception I get a segfault instead.

Thoughts?

**Comment by mvdwerve** [comment]
From what space are you throwing an exception? PHP userspace or from the C++ side of things? The latter is not supported AFAIK.

**Comment by gnat42** [comment]
Well, I followed the documentation so I'm throwing from C++ but using the PHP::Exception(); Like so:

```
void PdfWriter::__construct(Php::Parameters &params) {
    struct stat buffer;
    if (stat (params[0], &buffer) != 0) {
        throw Php::Exception("File doesn't exist?");
    }

    _inputFileName.assign(params[0].stringValue());
    _outputFileName.assign(params[1].stringValue());
    writer.ModifyPDF(_inputFileName, ePDFVersion14, _outputFileName);

    initializeFonts();
}
```
If in php I do new PDF\PdfWriter("/path/to/non-existent/file.pdf");
I get the following output:

```
poppler/error: Couldn't open file './File.pdf': No such file or directory.Segmentation fault (core dumped)
```

**Comment by mvdwerve** [comment]
Oh damn. That should work afaik. Will take a look at it somewhere this week, thanks!

**Comment by gnat42** [comment]
Hello,  Not sure what has happened but it now throws without a segfault. I was working on another issue where I needed to throw an exception and it was working perfectly. So maybe a transient issue with a particular PHP version?
