### ISSUE TITLE
libphpcpp.a/so in a subfolder of the home dir?

### ISSUE THREAD

**Issue by Haasrobertgmxnet** [CopernicaMarketingSoftware/PHP-CPP#370]
Is there a possibilty to use libphpcpp.so or libphpcpp.a loocally on a webserver without storing it in /usr/lib or /usr/local/lib? (Because I have no admin permissions) Rather I want to store the libphpcpp.a/so locally in in a subfolder of ma home directory. The g++/ld looks for libraries in /usr/lib etc. That's a problem. Changing the bash_profile file (LD_LIBRARY_PATH=~/lib and export LD_LIBRARY_PATH) doesn't seem to have any effect.

**Comment by EmielBruijntjes** [comment]
No. You must own the webserver to be able to tell it to run unprotected native code. It would be a security leak if regular users could to do this too.

**Comment by sjinks** [comment]
@Haasrobertgmxnet, try passing `-Wl,-rpath` option to the linker.
