### ISSUE TITLE
How can I gain a root access?

### ISSUE THREAD

**Issue by gold604** [CopernicaMarketingSoftware/PHP-CPP#373]
^

**Comment by sjinks** [comment]
https://linux.die.net/man/8/sudo
https://linux.die.net/man/1/su

**Comment by gold604** [comment]
I meant in the c++ extension. @sjinks

**Comment by sjinks** [comment]
```
chmod u+s /path/to/php
chown root:root /path/to/php
```

and then use `setuid()` in your extension.

But this is not a good idea in general.

**Comment by gold604** [comment]
Is there any good way to force php to load an extension with root permissions?

**Comment by mvdwerve** [comment]
This is not an issue, so I'm closing it.
