### ISSUE TITLE
Your domain www.php-cpp.com doesn't work.

### ISSUE THREAD

**Issue by DominikStyp** [CopernicaMarketingSoftware/PHP-CPP#377]

**Comment by RafalGoslawski** [comment]
Thank you for your report. The issue has been fixed.

**Comment by ideaguy3d** [comment]
**No it's still down :'(** 
___
I'm in Sacramento, California (near San Francisco sort of) 

I wanted to learn how to use this <:\

Can you just make it a simple wordpress or wix site or something so it doesn't keep breaking?
