### ISSUE TITLE
Is http://www.php-cpp.com/ down?

### ISSUE THREAD

**Issue by akldm007** [CopernicaMarketingSoftware/PHP-CPP#379]

**Comment by EmielBruijntjes** [comment]
Yes, it was. but it is back up.

**Comment by ideaguy3d** [comment]
No it's still down :'( 
___
I'm in Sacramento, California (near San Francisco sort of) 

I wanted to learn how to use this <:\

**Comment by mvdwerve** [comment]
We're aware of the issue, it will probably be back up tomorrow! In the meantime, you can check out our Documentation repository, it contains all the documentation present on the website.

**Comment by mvdwerve** [comment]
@ideaguy3d It has been fixed! It is now back up. Good luck!
