### ISSUE TITLE
[Question] Do I have to import all .so ?

### ISSUE THREAD

**Issue by flavienbwk** [CopernicaMarketingSoftware/PHP-CPP#386]
Hello,

To play my C++ extension in PHP, do I have to import all the .so used for my program inside the PHP extensions directory ?

I ask you that because PHP returns this error : 
`PHP Warning:  PHP Startup: Unable to load dynamic library '**PATH_TO_PHP_EXTENSIONS_DIR**/myprogram.so' - libcryptopp.so.7: cannot open shared object file: No such file or directory in Unknown on line 0`

In which `libcryptopp.so.7` is a dynamic library used by my program. 

Thank you.

**Comment by EmielBruijntjes** [comment]
The *.so files should be in a location where all the other *.so files are too. This often is /lib, /usr/lib and /usr/local/lib.
