### ISSUE TITLE
Not understanding declaration of optional parameter

### ISSUE THREAD

**Issue by flavienbwk** [CopernicaMarketingSoftware/PHP-CPP#387]
Hello,

Could you do an explicit example of how to declare optional parameters with PHP-CPP ?
I don't understand how to do this in your documentation.

Thank you.

**Comment by EmielBruijntjes** [comment]
If you do not specify the parameters, they are optional. It is always possible to pass more parameters to functions. Inside the C++ function you can simply check params.size() to find out how many parameters a user has passed:

```c++
void myFunction(Php::Parameters &params)
{
    // check how many parameters the user has passed
    if (params.size() == 0)
    {
        // user did not pass any parameters, so we assume a default parameter
        // @todo add your own implementation
    }
    else
    {
        // user did pass a parameter, use it
        Php::Value param = params[0];
        // @todo add your own code
    }
}
```
