### ISSUE TITLE
Error with zend

### ISSUE THREAD

**Issue by jookovjook** [CopernicaMarketingSoftware/PHP-CPP#392]
Using PHP-CPP with my cmake project produces the next errors during building:

```
Undefined symbols for architecture x86_64:
  "_OnUpdateString", referenced from:
      Php::Ini::fill(_zend_ini_entry_def*, int) in libphpcpp.a(ini.o)
  "___zend_malloc", referenced from:
  ...
  ...
  ...
  "_zend_string_tolower", referenced from:
      Php::LowerCase::LowerCase(_zend_string*) in libphpcpp.a(value.o)
  "_zend_throw_exception", referenced from:
      Php::process(Php::Exception&) in libphpcpp.a(classimpl.o)
      Php::process(Php::Exception&) in libphpcpp.a(callable.o)
  "_zend_unregister_ini_entries", referenced from:
      Php::ExtensionImpl::shutdown(int) in libphpcpp.a(extensionimpl.o)
  "_zend_update_property", referenced from:
      Php::Value::setRaw(char const*, int, Php::Value const&) in libphpcpp.a(value.o)
  "_zend_write", referenced from:
      Php::StreamBuf::sync() in libphpcpp.a(streambuf.o)
ld: symbol(s) not found for architecture x86_64
```

System: macOS High Sierra 10.13.6 

What I've done:
- built php from [php.net](http://php.net/get/php-7.1.21.tar.gz/from/a/mirror)
- built php-cpp from this repo
- linked php-cpp with my cmake project using `target_link_libraries(... phpcpp ...)`

Seems like something like`zendlib.a` was missed during build steps..

Also tried to build php with (`--without-iconv --enable-embed`), didn't help.

Any ideas?

**Comment by mvdwerve** [comment]
These are provided by PHP. Are you sure you are compiling a shared library, not an executable?

**Comment by jookovjook** [comment]
@mvdwerve thank you fir your help!
Seems like the issue was connected to php.

Found a dirty solution:

Produced `libzend.dylib` from php sources by myself:
- Created `CMakeLists.txt` inside `php/Zend` frolder with content:
```
cmake_minimum_required(VERSION 3.10)
project(zend)
set(CMAKE_CXX_STANDARD 11)
add_library(zend SHARED
        zend_alloc.c
        zend_alloc.h
        #...
        # There should be the list of all *.cpp, *.c and *.h file from php/Zend folder
        #...
)
```
- Built zendlib:
```
mkdir build
cd build
cmake ..
```
- Copied produced `libzend.dylib` file to my project
- Also, there was an Error referred to `php_error_docref` while building the project (maybe php versions mismatch)
- Commented line
`// php_error_docref(NULL, E_NOTICE, "Error while unserializing");`
in `PHP-CPP/zend/classimpl.cpp`
- Rebuilt PHP-CPP
- Linked PHP-CPP and Zend via `target_link_libraries(... phpcpp libzend.dylib ...)`

## **BUT**
now getting the next error while building my project:
```
...
[ 96%] Linking CXX shared library libexample-php.dylib
cp: /etc/php.d: Permission denied
...
```

**Comment by jookovjook** [comment]
Solved:
changed `set(PHP_CONFIG_DIR /etc/php.d)` to `set(PHP_CONFIG_DIR /usr/local/php<version>/php.d)` in `CMakeLists.txt` in my project.
