### ISSUE TITLE
Dynamic library signing on MacOS Mojave

### ISSUE THREAD

**Issue by abiusx** [CopernicaMarketingSoftware/PHP-CPP#396]
The .so file generated by PHPCPP is not loadable via dyld (PHP) because it is not signed:

> php --php-ini ./php-qt-ng.ini test.php
> PHP Warning:  PHP Startup: Unable to load dynamic library '/Users/user/Desktop/phpqt-ng/php-qt-ng.so' - dlopen(/Users/user/Desktop/phpqt-ng/php-qt-ng.so, 0x0009): code signature in (/Users/user/Desktop/phpqt-ng/php-qt-ng.so) not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. in Unknown on line 0
>

**Comment by yumuchen8** [comment]
i have met the same problem,if you have solved the problem, pls tell me

**Comment by robocoder** [comment]
Ad-hoc sign it with:
```
% codesign -s - '/Users/user/Desktop/phpqt-ng/php-qt-ng.so'
```

**Comment by yumuchen8** [comment]
我已收到邮件！谢谢！
