### ISSUE TITLE
php passthru function

### ISSUE THREAD

**Issue by arshidkv12** [CopernicaMarketingSoftware/PHP-CPP#403]
How can I eexecute `php passthru() or exec()` function in c++;

**Comment by arshidkv12** [comment]
Thanks
Actually I want execute PHP code in c++. 

Example :

```$str = "echo 'hi'; ";
some_custom($str);
```

I will modify php string in c++ `some_custom` function.

**Comment by EmielBruijntjes** [comment]
Don't do that. If you want to call PHP functions, write a PHP script. PHP-CPP was developed to be able to call C++ functions from PHP scripts, and not the other way around.

But there is a Php::call("php_function") that can be used. Although it would be completely ridiculous to use it for exec() as it would be much, much, much more efficient to directly call the exec() system call, and it would also be much more efficient to call exec() directly from a PHP script.

**Comment by arshidkv12** [comment]
Thank you.. 
I have one doubt. How to stream PHP script ? 
I am planning my own syntax in PHP.

**Comment by EmielBruijntjes** [comment]
I do not even know what streaming a PHP script means. PHP-CPP cannot be used to extend the PHP syntax.

**Comment by arshidkv12** [comment]
Please check following code.

PHP:-

```$str= "echo 'hi';";

some_cpp($str);```

I want execute function without return. How can I achieve ?

Thanks
