### ISSUE TITLE
Not working on different Linux distrod

### ISSUE THREAD

**Issue by arshidkv12** [CopernicaMarketingSoftware/PHP-CPP#404]
Hi,
I built extension in Ubuntu 64 bit is. It is working fine. But this .so file can't load on cloud Linux PHP.

**Comment by EmielBruijntjes** [comment]
Not enough information to reproduce or solve issue.

**Comment by arshidkv12** [comment]
How to reproduce?
Build php extension from Ubuntu and upload this extension (.so file) to cloudLinux.  This extension can't load. How to solve issue? I want build extension from different distros ? 

I am planning to ship my extension to nontechnical people.

**Comment by arshidkv12** [comment]
Sorry for my noob questions.
Can I execute .so file without libphpcpp.so in my host server ?

**Comment by mvdwerve** [comment]
Yes you can, but you'd need to statically compile the library with -fPIC and statically link that into your .so file. This is not advised if you are going to create multiple extensions though, since it will be in memory multiple times.
