### ISSUE TITLE
Build paths are hardcoded

### ISSUE THREAD

**Issue by joeyhub** [CopernicaMarketingSoftware/PHP-CPP#412]
```
ifeq ($(UNAME), Darwin)
  INSTALL_PREFIX                =       /usr/local
else
  INSTALL_PREFIX                =       /usr
endif

INSTALL_HEADERS                 =       ${INSTALL_PREFIX}/include
INSTALL_LIB                     =       ${INSTALL_PREFIX}/lib
```

It would be great instead to have those as defaults, if the user hasn't set the install prefix. Hardcoding things like this makes it very hard to package.

**Comment by mvdwerve** [comment]
It will get overridden if called like `make INSTALL_PREFIX=/usr/custom/dir install` afaik, so that's one way you could do that. If we alter it to `?=`, the environmental variables will also get taken into account, which might not be what we want.

**Comment by joeyhub** [comment]
Yes, this one is my bad for not understanding/forgetting that you can override the variables for make like that.
