### ISSUE TITLE
Project size

### ISSUE THREAD

**Issue by DanStorm** [CopernicaMarketingSoftware/PHP-CPP#437]
Love this project, thanks for making it a pleasure to use! 

Quick question about the directory size. I will be including php-cpp in my project repo for deployment purposes. Bitbucket repos have a 2GB  limit. I am wondering if there is any cruft I can remove from the php-cpp directory to reduce its size from 83MB and not affect `make && sudo make install`. `/documentation` and `/examples` clearly, but they don't account for very much. If the answer is nothing else, I am prepared to accept that :) just curious.

**Comment by EmielBruijntjes** [comment]
The PHP-CPP library is way smaller than 2GB and also way smaller than 83MB.
