### ISSUE TITLE
How to deal with structs

### ISSUE THREAD

**Issue by Nek-** [CopernicaMarketingSoftware/PHP-CPP#455]
Hello guys, I'm trying your tool (which looks great with awesome doc, nice work over here woow).

I wanted to create an extension for Box2D. But they use classes, as well as struct. (which should be translated in PHP as class I assume) But I didn't see anything related to struct management inside your documentation. Maybe this is not supported?

Thanks :)

**Comment by sallyx** [comment]
Structs is the same as class in c++, only all members are public by default.  There are no structs in PHP. So, there is nothing to document in PHPCPP i guess..
