### ISSUE TITLE
Best way for exporting C++ class to PHP?

### ISSUE THREAD

**Issue by gtamas** [CopernicaMarketingSoftware/PHP-CPP#461]
So I have a C++ class which is final, let's say it's called Presentation.
I want to make this class available in PHP.

What's the best way to do this?

Because of final, I cannot create a derived class using multiple inheritance.:

`
class myClass : public Php::Base,  public Presentation
` 

However I can create a custom class which then instantiates Presentation and it acts as a proxy, like:

```
class MyClass : public Php::Base {
private:
    Presentation* _pres;

public:
   MyClass() {
   _pres = new Presentation();
}

   Php::Value method() {
     return _pres->someMethod();
  }
}
```

So I can proxy this way, but is there a a better way? Can I somehow make Presentation with all its public methods available for PHP without writing such proxy?

Thanks in advance!

**Comment by EmielBruijntjes** [comment]
No. There is no way for PHP-CPP to understand your class and know which methods to expose, and how you would like them to behave in a PHP context.
