### ISSUE TITLE
How to convert custom types to Php::Value?

### ISSUE THREAD

**Issue by gtamas** [CopernicaMarketingSoftware/PHP-CPP#462]
I have an array or XY objects. How do I convert that to Php::Value?

This seems to work with simple arrays like {16, 2, 77, 40, 12071}, but if the array has this type: System::ArrayPtr<System::SmartPtr<Aspose::Slides::ISlide>>, conversion to Php::Value fails.

I'm not a C++ person, so sorry if the question is dumb :)

Basically I just wanna know if it's possible to convert custom complex types to Php::Value somehow or Php::Value supports only primitives and simple objects and arrays of objects / primitives?

Thanks in advance!

**Comment by EmielBruijntjes** [comment]
If you are not a C++ person, I would say that it is then impossible. Otherwise you need to write the code to convert the objects all the way down to objects and/or arrays of the pimitive types that PHP supports.
