### ISSUE TITLE
Is it possible to use Smart Pointers with Php::Object()?

### ISSUE THREAD

**Issue by gtamas** [CopernicaMarketingSoftware/PHP-CPP#466]
Question from a C++ beginner:

When I return Php::Object("SomeClass", value) I can use normal pointers, but it seems smart pointers are not supported.
So the following fails:

```
    Php::Value NotesSlideManager::get_NotesSlide() {
       ....
        auto phpSlide = std::make_unique<NotesSlide>(slide);  // doesn't work
        return Php::Object("NotesSlide", phpSlide);
    }
```

Is there any way to make something like this work? I only want to use smart pointers to make sure the memory won't leak, but maybe there is a better way? 

Btw, what if I return a normal pointer:

`        NotesSlide * phpSlide = new NotesSlide(slide); `

This works, but wouldn't this create a memory leak? I mean, I have no way to call delete later.

Thanks in advance!

**Comment by gtamas** [comment]
Guys, any help please?

**Comment by EmielBruijntjes** [comment]
See also http://www.php-cpp.com/documentation/variables

If you create an instance with "new" (like new NoteSlide()") and you then pass the pointer to Php::Object, the PHP-CPP library takes over ownership of your object and will make sure it is destructed (with delete) when it is no longer needed. No memory leak, an no need for smart pointers.

Note that after passing your pointer to Php::Object, that you should no longer destruct the object yourself. Ownership has been transferrred to PHP-CPP.

**Comment by gtamas** [comment]
Great, thank you!
