### ISSUE TITLE
How to export Enums?

### ISSUE THREAD

**Issue by gtamas** [CopernicaMarketingSoftware/PHP-CPP#475]
Hi!

Just a simple question.
How can create a function that returns an enum from CPP land to PHP land?

For example: 

```
     Php::Value SomeClass::getFillType()
    {
        enum rgb { red, green, blue };
        // is there a way to export rgb to PHP?
    }
```

**Comment by piotrslupski** [comment]
@gtamas I think it may be impossible as PHP does not support enum types. Its best to use a library for enums.

**Comment by EmielBruijntjes** [comment]
Indeed.

**Comment by gtamas** [comment]
OK Thanks guys!
