### ISSUE TITLE
How to use pure C++

### ISSUE THREAD

**Issue by fedushok** [CopernicaMarketingSoftware/PHP-CPP#476]
Good day!
I want to divide my extension code on two parts.
The first part will do almost the entire amount of my task work and will be written on pure C++. Implementation of my task needs complex data and code structure that is why I have to use classes.
The second part will get input data and output results of the first part to PHP.
This code structure allows to use C++ for the main goal activity and to use very simple PHP extension API to pass input data and to output the result. Now I am planning how make my extension and I have the following question.
How to work with memory for class objects? I mean that according to [PHP extension manual](https://www.zend.com/resources/writing-php-extensions) and [PHP internals book](https://www.phpinternalsbook.com/php7/memory_management.html) memory management is specific. That is why it is recommended to use not standard pair: emalloc, efree. But for class objects I now only new and delete.

**Comment by EmielBruijntjes** [comment]
I simply use new and delete and ignore the PHP memory management. It means that your script might overflow the max-memory setting of PHP (but other libraries that PHP already make use of do exactly the same, so that is not so much an issue, i assume)

**Comment by fedushok** [comment]
Thank you for your reply. 
Of course it is not an issue. But it would be great if you describe your ideas in your documentation about how to use pure C++ classes. It is very seductive to go further than just exporting C++ classes to PHP.
Tell me, please, what open source libraries use C++ (not C) (preferably with C++ classes).

**Comment by EmielBruijntjes** [comment]
The PHP-CPP library is the glue between PHP space and C++ space. The moment that your C++ function has been called by PHP-CPP, you can use all the features and constructs of C++ that you want. And because C++ is essentially a superset of C, you can also call all the C code that you want. From my perspective there are no limitations or guidelines.
