### ISSUE TITLE
Generating stub files for PHP extension

### ISSUE THREAD

**Issue by gtamas** [CopernicaMarketingSoftware/PHP-CPP#478]
I know there are open source tools for this, like this one:

https://github.com/sasezaki/php-extension-stub-generator

However, these tools only generate:

- Function signatures
- Method signatures
- Classes
- Namespace info

Missing data:

- Function / method return types
- Description of function parameters 
- Detailed info about classes (like descriptions)

Is there any way to add more detailed information about my classes / functions and methods in C++ code? For example can I make my code comments available for PHP somehow? Or does PHP-CPP offer some API to export more info about my code?

**Comment by EmielBruijntjes** [comment]
No.
