### ISSUE TITLE
Do std::mutex work if I export it by phpcpp?

### ISSUE THREAD

**Issue by stereomatchingkiss** [CopernicaMarketingSoftware/PHP-CPP#482]
As the title mentioned, do it work if I export std::mutex by phpcpp? The php7.4.3 do not build with multi-thread support.

Pseudo codes:

```
class php_mutex : public Php::Base
{
public:
  void lock() { mutex_.lock(); }
  void unlock() { mutex_.unlock(); }

private:
  std::mutex mutex_;
}

//register as usual
```

Then use it in the php like

```
$mutex = new php_mutex;

$mutex.lock();
//some operations
$mutex.unlock();
```

Could this work? 

I use std::threads and std::mutex in c++, those algorithms export to php works fine, but there are some algorithms 
need to pass in the callback to customize the behavior, would be great if the std::mutex export like that could works well
in php, codes looks like

```
$mutex = new php_mutex;

algo->detect(img, function($outputs) use($mutex)
{
   //do something
   //.................
   $mutex.lock()
   
   //do something
   //..................
   $mutex.unlock()    
});
```

**Comment by EmielBruijntjes** [comment]
I see no reason why this should not work. 

But you could ask yourself whether you indeed want this: if PHP-space is single threaded, but your PHP-extension _internally_ uses std::thread to run things in multiple threads (which is ok), would it in that case not be better to treat this as an implementation-detail of your extension and encapsulate it completely, meaning that you do not expect PHP user space scripts to worry about mutexes and handle that completely internally in your extension?

But that is mainly an architectural discussion. Technically, I see not reason why exposing std::mutex to PHP space would be wrong.

**Comment by rwols** [comment]
You also risk a deadlock if the code between your lock and unlock throws an exception. Better to just keep it an implementation detail.
