### ISSUE TITLE
Supporting generators / yield

### ISSUE THREAD

**Issue by marcinrosinski** [CopernicaMarketingSoftware/PHP-CPP#484]
Hi, 

is there a way for PHPCPP to support generators/yield the same way it is working under PHP right now: https://www.php.net/manual/en/language.generators.syntax.php

so one can have a C++ extension class that has a method that iterates through an iterator/array and yields it results into PHP script? e.g.

```
<?php foreach($myCppExtension.iterate() as $id => $val){...}
```

Checked in your manuals but couldn't find anything about generator support unless I have missed something?

**Comment by EmielBruijntjes** [comment]
No there is no such equivalent. C++ does not have a yield-mechanism as far as I know. 

Conceptually, Generators are syntactic sugar, and you can achieve a more or less similar behavior using iterators (although with more lines of code).
