### ISSUE TITLE
Release v2.3.0 compile error on php7.0 7.1

### ISSUE THREAD

**Issue by TedLiu1991** [CopernicaMarketingSoftware/PHP-CPP#492]
New release v2.3.0 compile error on php7.0 7.1 
classimpl.cpp:307:35 error :'zend_empty_string' was not  declared in this  scope

**Comment by sahilrajput03** [comment]
Is this issue resolved?
![image](https://user-images.githubusercontent.com/31458531/166662235-bdb4ad4a-7634-4204-a987-cc5d1c3b2f78.png)

**Comment by carlos-granados** [comment]
There is a maintained fork where a PR to fix this issue has been merged. You can find it here: https://github.com/fast-debug/PHP-CPP

**Comment by EmielBruijntjes** [comment]
We will not adding 7.0 support.
