### ISSUE TITLE
Support for PHP 8.1 

### ISSUE THREAD

**Issue by cayolblake** [CopernicaMarketingSoftware/PHP-CPP#493]
Hello,

Any plans for support on PHP 8.1 ?

**Comment by henrywood** [comment]
There is a PR here to add support for PHP 8.1:

[PHP 8.1 support](https://github.com/NobletSolutions/PHP-CPP/pull/2)

It seems to work ok with my extensions !

**Comment by carlos-granados** [comment]
There is a maintained fork which has been updated to PHP 8.2, you can find it here: https://github.com/fast-debug/PHP-CPP

**Comment by robocoder** [comment]
Fixed in PHP-CPP 2.4.0 (3d791e05c2655facc556d89565ead4f71c4c6217)

**Comment by EmielBruijntjes** [comment]
We have PHP 8 support now indeed
