### ISSUE TITLE
PHP v8

### ISSUE THREAD

**Issue by iliauta** [CopernicaMarketingSoftware/PHP-CPP#500]
Hi 

is PHP CPP compatible with PHP 8?

**Comment by carlos-granados** [comment]
There is a maintained fork which has been updated to PHP 8.2. You can find it here: https://github.com/fast-debug/PHP-CPP

**Comment by scorninpc** [comment]
another one!

Sad to see this repo not updated. alot ppl forking and doing nice things. Now we have windows build, php 8.1 and alot improvements

**Comment by vahidalvandi** [comment]
please add support php 8.0

**Comment by carlos-granados** [comment]
@vahidalvandi there is a maintained fork which has support for php 8+ https://github.com/fast-debug/PHP-CPP

**Comment by robocoder** [comment]
Fixed in PHP-CPP 2.4.0 (3d791e05c2655facc556d89565ead4f71c4c6217)
