### ISSUE TITLE
MAINTAINED FORK AVAILABLE

### ISSUE THREAD

**Issue by carlos-granados** [CopernicaMarketingSoftware/PHP-CPP#506]
This repository has been forked into a version which will be maintained and updated properly with any new PRs and kept up to date with newly releases PHP versions. You can find this fork here: 

https://github.com/fast-debug/PHP-CPP

**Comment by yazeed** [comment]
Thank you for sharing this!

**Comment by robocoder** [comment]
The original contributor attributions are lost in that fork. The "right way" would be to add the other committers' forks as remote origins, and then cherry-pick from them.

**Comment by EmielBruijntjes** [comment]
Closing this, as the intention is to keep this main branche up to date too
