### ISSUE TITLE
Calling serialize() from C++ 

### ISSUE THREAD

**Issue by Ekliptor** [CopernicaMarketingSoftware/PHP-CPP#512]
How can I call PHP's `serialize()` function from C++?

I'm aware of the Serializable interface and how to implement it: https://www.php-cpp.com/documentation/magic-interfaces

But the example then calls `serialize()` in PHP. Say I have a `Php::Value `in my C++ code, how do i serialize it without switching context?

**Comment by EmielBruijntjes** [comment]
What do you mean by "without switching context"?

Most functions can be called like this:
```
auto result = Php::call("serialize", somevalue);
```
