### ISSUE TITLE
__get and other magic methods are broken in PHP8

### ISSUE THREAD

**Issue by ebikt** [CopernicaMarketingSoftware/PHP-CPP#523]
Due to C++ automatic conversion of  pointer to bool, magic methods as __get, gets Php::Value with value `True` instead of the name of accessed property in PHP8. Moreover comparing them to `const char *` imediately leads to segfault, as such comparison fails when Php::Value is not string.

#522 fixes void* to bool conversion, which is sufficient to have __get working.

**Comment by EmielBruijntjes** [comment]
Thanks for your contribution
