### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by pierrejoye** [CopernicaMarketingSoftware/PHP-CPP#57]
Hi,

As part of making php-cpp builds using config file, I began to port it to windows (using vc13 and later vc11 to match upstream windows binary).

1st result:

https://gist.github.com/pierrejoye/593d8bf8ba3c5a81987c

Looks like some cpp features used need some tweeks.

besides:

1st config.w32 (pretty much the same then for config.m4):

// vim:ft=javascript
// $Id$

ARG_ENABLE('php-cpp', 'Enable php-cpp library', 'no');

if (PHP_PHP_CPP != "no") {
    ADD_SOURCES("sapi/php-cpp/src", "argument.cpp base.cpp callable.cpp classbase.cpp exception.cpp global.cpp globals.cpp \
                 hashmember.cpp iterator.cpp members.cpp modifiers.cpp namespace.cpp object.cpp origexception.cpp \
                parameters.cpp streambuf.cpp streams.cpp super.cpp value.cpp valueiterator.cpp", "phpcpp");
    SAPI('phpcpp', 'src/extension.cpp', 'php' + PHP_VERSION + 'phpcpp.lib');
//  PHP_INSTALL_HEADERS("sapi/phpcpp", "src/*.h");
}

it will allow to build php-cpp as part of php as a "sapi", which makes allows some optimizations later. Once it works I will try to provide another one to rely only on phpize, so php-cpp can be distributed easily.

**Comment by atvise** [comment]
Hi,

with the newest sources if got following errors:

2>\php-cpp\zend\compileroptions.h(37): error C2065: 'tsrm_ls' : undeclared identifier
2>\php-cpp\zend\compileroptions.h(37): error C2227: left of '->compiler_options' must point to class/struct/union/generic type
2>\php-cpp\zend\compileroptions.h(40): error C2065: 'tsrm_ls' : undeclared identifier
2>\php-cpp\zend\compileroptions.h(40): error C2227: left of '->compiler_options' must point to class/struct/union/generic type
2>\php-cpp\zend\compileroptions.h(49): error C2065: 'tsrm_ls' : undeclared identifier
2>\php-cpp\zend\compileroptions.h(49): error C2227: left of '->compiler_options' must point to class/struct/union/generic type
3>\php-cpp\hhvm\../include/value.h(135): error C3646: 'noexcept' : unknown override specifier
3>\php-cpp\hhvm\../include/value.h(147): error C3646: 'noexcept' : unknown override specifier
2>\php-cpp\zend\../include/array.h(111): error C3646: 'noexcept' : unknown override specifier
2>\php-cpp\zend\../include/object.h(123): error C3646: 'noexcept' : unknown override specifier

My Setting:
Windows 7(x64), Apache 2.4.10(x86), Php 5.6.3ts(x86) and Visual Studio 2013.

**Comment by ddeath** [comment]
Hi there,
any progres here? I tried to compile it in VC 2013 but ended up with 2300 errors...

**Comment by EmielBruijntjes** [comment]
There are people who have managed to compile it under Windows, but I'm not sure how they did it. Sadly, nobody sends in pull requests that solves this problem. You might try http://www.mingw.org/

**Comment by atvise** [comment]
@ddeath: I managed to compile it under VC 2013. I made also some fixes and I will make some pull requests this Fr.

**Comment by ddeath** [comment]
@atvise Thanks, that would be awesome. I owe you a beer. So when you will have a way to Slovakia contact me :100:

**Comment by atvise** [comment]
@ddeath As promised I have uploaded some pull requests for the MSVC issues ;) Your welcome :smile: I will :ok_hand: :beer:

**Comment by ddeath** [comment]
@atvise Thanks, I do not get any errors during compilation, as it starts to linking... 125 errors

    LNK2001: unresolved external symbol __imp___zval_copy_ctor_func	C:\phpcpp\classimpl.obj	phpcpp

Not exactly sure which library I am not linking. Any idea?

**Comment by atvise** [comment]
You'r welcome :smiley: 

I'm linking following libraries:
php5ts.lib
phpcpp.lib
phpcpp-common.lib

Which version of php do you use ?

**Comment by ddeath** [comment]
I tried 5.6.6, 5.5.22, 5.4.38 hmm I do not link phpcpp-common.lib where dit it come from? :D

**Comment by atvise** [comment]
I'm using my own CMake script to compile PHP-CPP so my phpcpp libs are probably the same as your phpcpp.lib. Did you use the CMake files from the branch "cmake" ?

**Comment by ddeath** [comment]
Yes I do, but I had to change it a little bit because it does not work. I removed c++11 support check, and
   install(TARGETS phpcpp LIBRARY DESTINATION lib)

changed to 
    install(TARGETS phpcpp DESTINATION lib)

and also added some include folders...
But it do not have any phpcpp-common.lib in release folder...

Here is pastebin for cmake http://pastebin.com/7pTBsHde

Thanks for your time

**Comment by atvise** [comment]
I think it's the problem of php itself. I took me also a amount of time to get behind this errors. Look up following files: 
Zend/zend_modules.h
 - Add BEGIN_EXTERN_C() on line 125
 - Add END_EXTERN_C() on line 136
Zend/zend_object_handlers.h
- Move BEGIN_EXTERN_C() from line to 25

Now try again :)

Btw: I use also a customized cmake file and I myself generated the file phpcpp-common.lib. So you couldn't possible have this file or anyone else ;)

**Comment by ddeath** [comment]
Hey thanks :D It helps a little it :D I moved from 8 errors to 6 :dancer: 

    Error	606	error LNK2019: unresolved external symbol "public: static void __cdecl Php::Functor::initialize(void * * *)"     (?initialize@Functor@Php@@SAXPAPAPAX@Z) referenced in function "private: bool __thiscall Php::ExtensionImpl::initialize(int,void * * *)"     (?initialize@ExtensionImpl@Php@@AAE_NHPAPAPAX@Z)	phpcpp
    Error	607	error LNK2019: unresolved external symbol "public: static void __cdecl Php::Functor::shutdown(void * * *)"     (?shutdown@Functor@Php@@SAXPAPAPAX@Z) referenced in function "private: static int __cdecl Php::ExtensionImpl::processShutdown(int,int,    void * * *)" (?processShutdown@ExtensionImpl@Php@@CAHHHPAPAPAX@Z)	phpcpp
    Error	608	error LNK2019: unresolved external symbol "__declspec(dllimport) struct _hashtable module_registry"     (__imp_?module_registry@@3U_hashtable@@A) referenced in function "class Php::ExtensionImpl * __cdecl Php::find(int,void * * *)"     (?find@Php@@YAPAVExtensionImpl@1@HPAPAPAX@Z)	phpcpp
    Error	609	error LNK2001: unresolved external symbol "public: virtual bool __thiscall Php::FatalError::report(void)const "     (?report@FatalError@Php@@UBE_NXZ)	phpcpp
    Error	610	error LNK2001: unresolved external symbol "public: virtual bool __thiscall Php::FatalError::report(void)const "     (?report@FatalError@Php@@UBE_NXZ)	phpcpp
    Error	611	error LNK1120: 4 unresolved externals	phpcpp

**Comment by EmielBruijntjes** [comment]
The undefined functions that you report are implemented in files that were later added to PHP-CPP: FatalError.cpp and Functor.cpp -- could it be that these files are not yet included in the Visual C++ project file?

**Comment by ddeath** [comment]
After I added Functor.cpp and FatalError.cpp, l got only one error:

    Error	80	error LNK2019: unresolved external symbol "__declspec(dllimport) struct _hashtable module_registry" (__imp_?module_registry@@3U_hashtable@@A) referenced in function "class Php::ExtensionImpl * __cdecl Php::find(int,void * * *)" (?find@Php@@YAPAVExtensionImpl@1@HPAPAPAX@Z)	phpcpp

Any ideas?

**Comment by atvise** [comment]
Hmm try to lookup "module_registry" in the file zend_modules.h this should be within the BEGIN_EXTERN_C() AND END_EXTERN_C() declarations.

**Comment by ddeath** [comment]
THanks you all :) Finaly I compiled it

**Comment by atvise** [comment]
awesome :+1: glad we could help :smiley:

**Comment by boomcol** [comment]
Hi, can you tell me how compile it in visual studio ? What need to do?  Thanks

**Comment by atvise** [comment]
Hi boomcol,

Let me sum up our previous conversations for you.

Use the cmake file from the cmake branch
Edit the cmake file so Functor.cpp and FatalError.cpp is added. 
(Someone should add a pull request which update the last modifications to the PHP-CPP sources)

Then lookup following files in your php directory:
Zend/zend_modules.h
    Add BEGIN_EXTERN_C() on line 125
    Add END_EXTERN_C() on line 136

Zend/zend_object_handlers.h
    Move BEGIN_EXTERN_C() from line to 25

and make shure "module_registry" file zend_modules.h is within the BEGIN_EXTERN_C() AND END_EXTERN_C() declarations.

* In general all " ... unresolved external symbol "__declspec(dllimport) ..." errors are from a missing or misplaced BEGIN_EXTERN_C() / END_EXTERN_C() declaration in the php files. (Someone should tell them)

Now you should be able to compile PHP-CPP :smile:

**Comment by ddeath** [comment]
In cmake branch are missing some libraries also - you have to add them as linker option. phpcpp.lib, php5ts.lib at least. And I had to define some c++ compilers flags in order to compile it...

**Comment by boomcol** [comment]
Thanks a lot :) , and once more, which version of php need to use ? or any can be used ?

**Comment by ddeath** [comment]
Well I used 5.5.22 but it should work with others as well

**Comment by boomcol** [comment]
Can`t compile, i haven`t worked with c++ before :unamused: and cmake installer say warning: PATH is too long

**Comment by edin** [comment]
Hi, thanks to atvise, i've compiled php-cpp using VS2013. Here is just some more info how to setup and compile it using vs2013: 

- Make sure you have setup PHP-SDK, in my case it was in folder  C:\php-sdk\phpdev\vc11\x86\php-src-php-5.6.3
- Update zend_modules.h and zend_object_handlers.h header files as per atvise comment above
- Run VS command promt, cd into php dir and recompile using nmake (type nmake and hit enter)
- Create new visual studio c++ empty project and import  zend/*.cpp and common/*.cpp
- Open project properties, navigate to Configuration Properties -> Genral and set Configuration Type to Dynamic Library
- At Linker section and add "C:\php-sdk\phpdev\vc11\x86\php-src-php-5.6.3\Release_TS" to additional library directories
- At Linker/Input section add Additional Dependencies for php5ts.lib
- At VC++ Directories add additional include directories for {sdk}/Zend, {sdk}/TSRM and {sdk}/main
- At C/C++/Preprocessor set additional Preprocessor Definitions to:
	_USE_32BIT_TIME_T 
	ZEND_DEBUG=1 
	WIN32 _DEBUG _WINDOWS 
	ZTS=1 
	ZEND_WIN32
	PHP_WIN32
	_CRT_SECURE_NO_WARNINGS
	
Also before i could compile i had to rename streambuff.cpp from common to something else, because there is streabbuf.cpp file in zend folder as well, and when VS creates object files they end up in Debug folder so one *.obj file gets overwriten and latter  linker error appears that StreamBuf::sync can't be resolved.

Hope this helps.

**Comment by boomcol** [comment]
Thanks, but i got an error when compiling (nmake) :( Could you show me how to do this by skype or teamviewer, I would be very grateful

**Comment by stooray1** [comment]
Hi there, I can't find branch with cmake. Can someone help? I am struggling to build with vs.

**Comment by boomcol** [comment]
try this https://github.com/atvise/PHP-CPP/tree/cmake

**Comment by stooray1** [comment]
Thanks! Now I will try to build it

**Comment by atvise** [comment]
Hi,

i've managed to build the current master branch (a5ca2f39c43b3bc67f62f73863a5c0c8beb45b2e) with PHP 7.1.3 (x64) Visual Studio 2015 /MD on Win10 but the linker will throw following errors when i use the php-cpp library:
```
error LNK2005: "int __cdecl _open(char const * const,int,int)" (?_open@@YAHQEBDHH@Z) already defined in phpcpp.lib(extension.obj)
 error LNK2005: "int __cdecl _sopen(char const * const,int,int,int)" (?_sopen@@YAHQEBDHHH@Z) already defined in phpcpp.lib(extension.obj)
...
```

I'll get following warnings when I build the php-cpp library:
```
warning LNK4006: "int __cdecl _open(char const * const,int,int)" (?_open@@YAHQEBDHH@Z) already defined in zval.obj; second definition ignored 
warning LNK4006: "int __cdecl _sopen(char const * const,int,int,int)" (?_sopen@@YAHQEBDHHH@Z) already defined in zval.obj; second definition ignored
...
```

Do any of you have the same problems or do you know how to fix it ? I would be grateful for any answers and help!

**Comment by gouchaoer** [comment]
@atvise could you tell us how to compile php-cpp for windows php7 step by step?

**Comment by fifothekid** [comment]
anybody has the cmake file?

**Comment by mvdwerve** [comment]
Going to close this now, as the CMake file has been merged.
