### ISSUE TITLE
PHP_VERSION_ID not set automatically.

### ISSUE THREAD

**Issue by RexValkering** [CopernicaMarketingSoftware/PHP-CPP#87]
When using the library in a PHP 5.5.9-1 environment, it seems to generate an error in PHP:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/functionvoid.so' -
/usr/lib/libphpcpp.so: undefined symbol: zval_property_ctor in Unknown on line 0
```

This is caused by the following code in zend/objectimpl.h:

```
#if PHP_VERSION_ID < 50399

    // tmp variable
    zval *tmp;

    // initialize the properties, php 5.3 way
    zend_hash_copy(_mixed->php.properties, &entry->default_properties, (copy_ctor_func_t) zval_property_ctor, &tmp, sizeof(zval*));

#else

    // version higher than 5.3 have an easier way to initialize
    object_properties_init(&_mixed->php, entry);

#endif 
```

PHP_VERSION_ID is not set automatically, so the first part of the if-statement is always evaluated, resulting in an error since zval_property_ctor() is no longer defined in PHP5.5.9-1. This is probably also true for the many other files in which this environment variable is used.

This should be fixed. Until then, putting

```
export PHP_VERSION_ID=50509
```

in your .bash_rc file seems to do the trick.

**Comment by linkaisheng** [comment]
赞
