### ISSUE TITLE
Using Php::out with Apache crashes

### ISSUE THREAD

**Issue by atvise** [CopernicaMarketingSoftware/PHP-CPP#90]
Hi,

i'm using Apache and PHP and I noticed that when I use:
 Php::out << content << flush();
and do multiple page requests the process will be terminated with this error: "AH00428: Parent: child process 2512 exited with status 255 -- Restarting."

My current solution for this problem is a std::mutex around it but then i do requests more or less sequentially and not simultaneously :(

Basically what I want to do is to generate the page with header depending on the current request and return it to the client:

// Set the headers
const size_t headerSize = headers.size();
for (size_t i = 0; i < headerSize; ++i)
  Php::call("header", headers[i]); // btw: is there any better way to set the header ?

// Set the content
Php::out << content;
Php::out.flush();

My Setting:
Windows 7(x64), Apache 2.4.9(x86), Php 5.5.12ts(x86) and Visual Studio 2013.

**Comment by weltling** [comment]
@martijnotto the commit b8a4b5fb2db6ef9860c4205cf90401e67b458f62 makes things not portable. Visual studio linker was never able to DLL export thread local data directly. Effectively `thread_local __declspec(dllexport)` puts two incompatible storage specifiers which Visual Studio won't even compile, see `include/streams.h`. Even leaving Visual Studio aside - thread_local should be automatically static, as by the standard.

An object like `Php::out`, that still needs to be available outside the binary, should encapsulate the thread safety part. Perhaps, PHP's own APIs can be also reused for some part, but in general there's probably no way around other than PHP-CPP to have own wrapper I/O classes. That's also the direction @atvise's thought goes to. Right now, VS build is just broken.

Just my 2 cents.

Thanks.
